### ISSUE TITLE
Split range files around ApproximateRangeSizeBytes

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1158]
In GeneralMetaRangeWriter, the hash of the key determines if the range should break at the current entry.
Each entry represents more than a single byte, hence name is misleading and implementation has a bug.

**Comment by guy-har** [comment]
The main problem with ApproximateRangeSizeBytes is that we get a wide variance of ranges, 
I ran a test on 70 million records and got ranges in all sizes between 4K and 400MB.
We need a solution with a smaller variance and some way to enforce MAX_SIZE

**Comment by arielshaqed** [comment]
The current solution has some issues.  This comment explains why a geometric distribution is a poor choice.

Currently we decide to stop after a given key with some probability which we want to be around 1/L, in order to get ~L records per range.  Indeed, if we stop after each element with probability p, then the expected time T to split -- i.e. the number of elements in the range -- is expected to be:
![expected geometric time is 1/p](https://user-images.githubusercontent.com/7802932/104302169-23c5dd80-54d1-11eb-81a1-fdb807202b5f.png)
which seems cool.

Unfortunately the _variance_ of a geometric distribution is *huge*.  Rather than go on about standard deviation -- which doesn't even explain just _how bad_ it gets, let's look at the distribution!  The probability of getting a piece of size <=k is:
![probablity of getting a piece of size up to k is 1-(1-p)^k](https://user-images.githubusercontent.com/7802932/104302824-ef9eec80-54d1-11eb-87ae-9261a85eef92.png)
This is the probability of getting a range of size up to k, and it is _shockingly large_.

Let's take p=1/50000.  Then the expected size of a range is 50000.  Here are the likelihoods of some sizes:

| k | probability of range having size <= k |
| --- | --- |
| 1e3 | 0.0198 |
| 1e4 | 0.181 |
| 1e5 | 0.865 |
| 2e5 | 0.982 |
| 3e5 | 0.998 |
| 1e6 | about 1 |

We want all pieces to be around 50000 lines, but over 1 in 6 will be over 200000 - 4 times as much!

**Comment by arielshaqed** [comment]
We _also_ proposed stopping after each path with probability inversely proportional to its size.  Here's a [gist that simulates expected sizes for this with a log-normal distribution](https://gist.github.com/arielshaqed/3a0080cfdad52a7086d133162b277efa).  While it does not vary wildly, as the standard deviation (`Sigma`) varies the expected file size goes _up_ (compare 0.1 with 3.0 for a wild difference), meaning there is no easy way to control the file size... especially not if the path size distribution is unknown.

(I also have a partial explanation why this is so that is based on [Wald's theorem](https://everything2.com/title/Wald%2527s+theorem); you end up needing to compute the expected time to stop by the above rule, which is clearly _not_ the expected path length (an "arithmetic average") but rather based more like the harmonic mean -- which can be very different.  But finishing this analysis is too much integration for too little gain; sorry.)

**Comment by itaiad200** [comment]
Just to make sure I followed. The punchline states that `over 1 in 6 will be over 200000`, but your numbers indicate a 0.982 probablity of being under that, which is more like 1 in 50, no?

**Comment by arielshaqed** [comment]
> Just to make sure I followed. The punchline states that `over 1 in 6 will be over 200000`, but your numbers indicate a 0.982 probablity of being under that, which is more like 1 in 50, no?

Yeah..., cannot count.  That's 1 in 55 :-(
Fixed!

**Comment by itaiad200** [comment]
OK that cleared up some things, GREAT analysis @arielshaqed !

Now that we have the numbers I feel pretty confident moving forward with this solution. 
If we're aiming for 10MB range size then getting a 40 MB file every 55 files isn't that of a big deal, and getting 100MB is (Ariel to keep me honest) 1 in 22,029.

The only thing that varies here is the length of the path, so we might need to adjust the algorithm to be proportional to the size of the actual written data, but nothing more than that.

**Comment by arielshaqed** [comment]
OK, I think we shall go back to the original plan.

# The Plan

Add 3 parameters:
- minimum range size (bytes)
- maximum range size (bytes)
- raggedness factor (entries)

Close (split) a range after adding an entry *if* any of these holds:
1. Next need to add an entire range (TODO: collect data to see whether we want to buffer some range entries to avoid this creating very small ranges). OR...
2. The current range size is >= maximum range size.  (SO the maximum is not really a maximum, we go one whole entry above it).  OR...
3. The current range is >= minimum range size and `hash(entry.Key) / maxHashValue  > 1/raggedness`.

- (1) means we always re-use a range when we can, and don't try to have a large range before it.  (Avoiding (1) in favour of enlarging the previous range means larger single range files, but a potentially quadratic growth in metadata size).
- (2) means we never have very large ranges :-)
- (3) means we don't split to very small sizes, and that there is some tendency to split ranges between different branches in the same places.  Ideally raggedness = (max_size - min_size) / average_entry_size -- but it works reasonably well within 3x (because the variance of a geometric distribution is so high).
- TODO: figure out a way to collect data from real installations to determine whether this strategy is good enough, and how to improve it.

Consider :-1:ing or :+1:ing to indicate how bad (or good) this sounds.
