### ISSUE TITLE
lakeFS run banner prints URL regardless to configurations

### ISSUE THREAD

**Issue by guy-har** [treeverse/lakeFS#1198]
When running lakeFS it prints a run banner to the command line.

```

     ██╗      █████╗ ██╗  ██╗███████╗███████╗███████╗
     ██║     ██╔══██╗██║ ██╔╝██╔════╝██╔════╝██╔════╝
     ██║     ███████║█████╔╝ █████╗  █████╗  ███████╗
     ██║     ██╔══██║██╔═██╗ ██╔══╝  ██╔══╝  ╚════██║
     ███████╗██║  ██║██║  ██╗███████╗██║     ███████║
     ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚══════╝

│
│ If you're running lakeFS locally for the first time,
│     complete the setup process at http://127.0.0.1:8000/setup
│

│
│ For more information on how to use lakeFS,
│     check out the docs at https://docs.lakefs.io/quickstart/repository
│

```

The URL to the setup process is fixed and does not change according to configurations

**Comment by ozkatz** [comment]
the message does say "if you're running lakeFS locally` :)
It's mostly because we can't really tell what DNS name will actually be accessible for the user - especially in the very likely scenario where lakeFS is running behind a load balancer. We can add a configuration value *just* for that, but I believe that's a bit of an overkill.

**Comment by guy-har** [comment]
I don't think we should add a configuration just for that, but I do think that taking the port from the configuration instead of printing 8000 can be nice.

**Comment by guy-har** [comment]
And maybe I missed something, but can't we just use the configuration we already have. `server.endpoint_url` ?

**Comment by ozkatz** [comment]
you could, but there is no setting of that name :)

My problem with the port suggestion, while it appears to make sense, is that if someone changes the `listen_address` setting to something non-default, they are probably not running locally, so chances are it'll be deployed behind a load-balancer (which in most likelyhood expose `:80` or `:443` instead of whatever custom port the server is actually listening on).

There's simply no way to guarantee a working URL here without the user explicity stating one.

**Comment by guy-har** [comment]
OK,
So I am closing this Issue.
Thanks
