### ISSUE TITLE
Graveler staging DB partitions don't respect naming conventions

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#1227]
table is called `graveler_staging_kv` but partitions are called `kv_staging_p0, kv_staging_p1, ...`. They should be prefixed by the name of the table.

**Comment by arielshaqed** [comment]
# breaking change, will require an expensive DB migration

... so I'm marking it as "required for release": the two best options are to do it before, or close it.  I'd rather *not* have to migrate users, also the DDL code for renaming is hairy because SQL for DDL is such a  very horrible no-good painful unpleasant dangerous _hard to test_ language.
