### ISSUE TITLE
openapi spec error for get branch commit log

### ISSUE THREAD

**Issue by gilandose** [treeverse/lakeFS#1288]
when using bravado I get an error when I run the following and trying to return the entire log:
client.commits.getBranchCommitLog(repository=repo, branch=master).result()
Looks to be it expects the first entry in the commit log to have a parent and it does not, and so returns a validation error, should the spec be more relaxed for the parent field?

I can return a commit log as long as I don't read first row ie 
client.commits.getBranchCommitLog(repository=repo, branch=master, amount=2).result()
```python
ValidationError: None is not of type 'array'

Failed validating 'type' in schema['properties']['results']['items']['properties']['parents']:
    {'items': {'type': 'string'}, 'type': 'array'}

On instance['results'][2]['parents']:
    None
```

**Comment by itaiad200** [comment]
It looks like more of a bravado issue than lakeFS, we do not mark any field in the returned [commit object](https://github.com/treeverse/lakeFS/blob/90c98d59cd7bed05a2bf6aa3f09a11405a97375d/swagger.yml#L170) as required.

However from lakeFS POV in such cases it doesn't make a difference to return an empty list instead of null object. @gilandose Would that work for you?

**Comment by gilandose** [comment]
yeah that would work wasn't a big deal to be honest just raised as I encountered with the default implementation. No problem either way

**Comment by ozkatz** [comment]
Should be fixed since migrating to rocks (we now always pass a `parents` array. Will be empty for the first commit in a repository, but this passes Swagger's validation rules).
