### ISSUE TITLE
Installation facts are not always collected

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#1345]
There are several occasions of installations that don't have any facts in the callhome db.
Need to understand why do they fail to send them.

**Comment by johnnyaug** [comment]
More than half of the cases where no facts are collected can be explained by the following scenario:
* User starts lakeFS with an empty DB.
* User runs setup through the API or UI (and **not** the CLI).
* User does not restart lakeFS ever.

Since we only collect metadata when the server starts (or when the setup runs from the CLI) - metadata for this installation is never sent.
