### ISSUE TITLE
Merge large changes performance

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#1439]
Merge currently is based on diff. Diff can skip common ranges if it identifies no changes between the two commits.
The problem is when we merge a commit with a large set of changes, like import, where are ranges which we can reference as is without applying Add of new records as part of diff iterator.

**Comment by ozkatz** [comment]
a concrete example: import-from-inventory being merged into a master branch which is nearly empty.

this merge will result in all (or almost all) ranges from the import branch being reused, but since we're using the diff iterator, we'll end up reading every record only to write it into a new range which will end up being the exact same. This takes time proportional to the size of the inventory.
