### ISSUE TITLE
lakeFS request IDs should be distinguishable from AWS request IDs

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#1607]
Make request IDs generated by lakeFS recognizable - either use a constant prefix, or some other way.

Motivation:
When receiving a stack trace from a customer, it may be useful to understand whether an error comes from S3 or from lakeFS.

e.g., looking at the following error, I would like to know where the error came from:
```
com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: The security token included in the request is invalid. (Service: AWSSecurityTokenService; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: a9f16ed8-0e04-46c6-87ee-3c43bfe844b2)
```

**Comment by arielshaqed** [comment]
@johnnyaug I'd like to take a crack at this, as part of a round of o11y improvements.

**Comment by arielshaqed** [comment]
Suggestion: use `lakefs-<nanoid>`, where nanoid is generated by `github.com/matoous/go-nanoid/v2`.  Nanoids are (much) shorter than UUIDs because they use more characters, they a bit easier to read out over a voice call (if you must), and starting with "`lakefs`" should give a pretty good hint of the source of the request ID.
