### ISSUE TITLE
Misleading error on branch creation with an invalid name

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#1634]
On branch creation via lakectl with an invalid branch name the following error is returned: 
`Error executing command: argument branchID: invalid value`
The expected input for `lakectl branch create` is the branch name and the source from which to create the branch, but the error refers to an invalid branch **id**. 

**Steps to reproduce:**
Try to create a branch from lakectl using an invalid branch name, e.g. 
`$ lakectl branch create lakefs://branching-models@testing-spark-3%.0 --source lakefs://branching-models@master`

**Comment by ortz** [comment]
hey @talSofer ,

There's a difference between how the CLI checks the branchID compared to the API alone.

The API does a syntax check using a quite straight-forward regular expression (see here: https://github.com/treeverse/lakeFS/blob/master/pkg/catalog/validate.go#L98)

The CLI has two phases, the first one it validates we get a URL using the net/url.Parser function (see here: https://github.com/treeverse/lakeFS/blob/master/pkg/uri/parser.go#L84) which doesn't accept % for instance.
Only if this validation is successful, it triggers a call to the API which run its own validation.

I think on taking this one as a "good first issue" and I wonder how to approach it.
IMO, I think consistency is more important and I would probably drop the validation in the CLI or align it with the same rules as the API, though I'm not sure we need two steps verification.
Due to the fact the API is already checking it, I wonder if that's something we'd like the CLI to cover at all.
Your thoughts?

**Comment by talSofer** [comment]
Hi @ortz !
I think that the two steps branch name validation done in the CLI code is useful because it is not repetitive and helps to report accurate errors. `lakectl` validates the input format as it expects to get it - as a URI, and the `createBranch` API call also validates the input it receives (branch name) and report an error. so when I look at the two errors you mentioned above it's actually helping me understand what went wrong. 

What's confusing to me is this error `argument branchID: invalid value: validation error`, as an end-user I dont' understand what branchID is. WDYT? 


To add more to this issue, I looked at what the UI does while creating a branch with an invalid name. and it does not report the error the API returns. I opened this issue to track that https://github.com/treeverse/lakeFS/issues/2839

**Comment by ortz** [comment]
I agree that this error message is confusing, the fact is that the CLI doesn't return it, it's the API.
I think that the terminology here is a bit confusing as it's the branch name (which maybe acts as ID also).

I'm trying to pin-point what's confusing in the error message, is it the part it says branchID instead of branch name? or the fact that we provide a lakeFS FQDN (lakefs://repo/branch) and get an error in response for only part of it that contains the branch name?

**Comment by talSofer** [comment]
> is it the part it says branchID instead of branch name? 
@ortz IMO, yes this is what's confusing. 

> or the fact that we provide a lakeFS FQDN (lakefs://repo/branch) and get an error in response for only part of it that contains the branch name
I think that this part is not confusing because when I try to create a new branch I understand what part of the URI represents the new name I chose.

**Comment by ortz** [comment]
@talSofer alright... pretty simple, I'll take this one to start with :)
thanks for the context and information.

**Comment by arielshaqed** [comment]
Generating error messages in the cli is somewhat strange. IMHO a UI should generate an error if input presented cannot be used to perform an api call. And all other cases should be handled by the API server.

There are several advantages to doing it this way. Among them :

* no need to upgrade clients in future to get better error messages. Users never upgrade their clients.
* support for all UIs.
* better o11y: operators can get an error log line for more errors.

That said,  I agree the error message from the API server... could be improved.
