### ISSUE TITLE
UI: Tag support (listing, viewing object tree and comparing)

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#1749]
Support Tags in lakeFS UI:

- [ ] Allow selecting tags in compare tab 
- [ ] Allow selecting tags in objects browser
- [ ] Dedicated "Tags" page that enumerates tags and allows filtering by tag ID

**Comment by shamikakumar** [comment]
Hey, could I have more information on this issue ?

**Comment by itaiad200** [comment]
Hey @shamikakumar, sure thing!
`tags` are a lakeFS feature that is a lot like Github's tags (see our repo [tags](https://github.com/treeverse/lakeFS/tags) for example) -  It allows you to mark a specific commit and address it using a short nickname (e.g. "v0.3.1") instead of a long random commit hash.
`tags` are already supported in lakeFS api, see our [OpenAPI](https://github.com/treeverse/lakeFS/blob/60fae405cdd44fb3d24c0d4eac16e525756a255e/api/swagger.yml#L1664) yaml for the CRUD operations.

This issue goal is to expose those capabilities in the UI as well, specifically the features that @ozkatz manifested above.

**Comment by itaiad200** [comment]
btw if you feel that the feature list is lacking, or that is too big to be implemented in a single PR, we are open to any suggestions.

**Comment by itaiad200** [comment]
You got it @shamikakumar

**Comment by shamikakumar** [comment]
hey @itaiad200 , I've been working on the dedicated tags page, do take a look and let me know -> https://github.com/shamikakumar/lakeFS/tree/feature/tag-support-%231749

**Comment by itaiad200** [comment]
Thanks Shamika, opened a [PR](https://github.com/treeverse/lakeFS/pull/2115) and will comment there.

**Comment by itaiad200** [comment]
Hey @shamikakumar ! Did you have a chance to look at the PR comments?

**Comment by itaiad200** [comment]
Hey @shamikakumar, is this still active?

**Comment by itaiad200** [comment]
Hey @shamikakumar , thanks for bringing this PR so far! I'm moving it back to planning to be picked up and continue from your great work here. Thanks for all your efforts!
