### ISSUE TITLE
Create temporary branches with random names

### ISSUE THREAD

**Issue by mikulskibartosz** [treeverse/lakeFS#1833]
When branches are used in an ETL job (for example, when Apache Spark processes the data), the name of the branch does not matter, so the client code could be simplified if LakeFS supported creating temporary branches with random names.

## Suggested API
In the REST API, it can be implemented as a POST request to the `/repositories/{repository}/branches/temp` endpoint with only the source in the request body. In the response, the API can return the randomly generated branch name.

## Benefits

* Users don't need to write code generating unique branch names for temporary branches that exist for a short time.

## Disadvantages

* It is a corner case. I am not sure whether you want to support such niche requirements.

**Comment by ozkatz** [comment]
Thanks @mikulskibartosz! That's an interesting idea. Since we already have a basic Spark client, I'm thinking perhaps this logic belongs on the client side:

`val tmpBranch = lakefs.createTempBranchFrom('my-repo', 'main')`

if this type of API makes sense, it can be done completely on the client side, utilizing existing APIs. Would love your thoughts on this approach.

**Comment by mikulskibartosz** [comment]
It is perfect!

**Comment by arielshaqed** [comment]
> It is perfect!

Closing: IIUC this is resolved.  Please re-open (_and accept my apologies_) if https://github.com/treeverse/lakeFS/issues/1833#issuecomment-828681074 is insufficient for you.
