### ISSUE TITLE
Question: Automatically commit objects for dedicated branches

### ISSUE THREAD

**Issue by D0mc3k** [treeverse/lakeFS#1834]
Hi folks,

we are using lakefs to ingest automatically data via Kafka Connect to Minio. We are currently evaluating a procedure to automatically commit objects in lakefs branches. Are you providing some kind of configuration to auto commit for specific branches or do you have a best practice approach to do that via WebHooks respecitvely the lakefs API in general?

Thanks in advance
Domcek

**Comment by itaiad200** [comment]
Thanks @D0mc3k for bringing this up.

I can see the added value for ingestion pipelines, where you would like commits to happen automatically (like every X mins, every Y new objects?) since objects are always being uploaded. 

There isn't a configuration for auto-committing of that sort to lakeFS. I don't think it should be too hard to support, @ozkatz wdyt? For now, you can use the commit API and call it every X mins by automating some logic on the client side.

**Comment by itaiad200** [comment]
depends on #2358
