### ISSUE TITLE
Metadata client doesn't work on Databricks

### ISSUE THREAD

**Issue by johnnyaug** [treeverse/lakeFS#1847]
Metadata client doesn't work on Databricks, probably due to a conflict in RocksJava version.

Steps to reproduce:
1. Have a public lakeFS installation ready (you can use Terraform), with a repository and a commit.
2. Start a Databricks cluster.
3. In the cluster configuration > _Libraries_ tab, click Install new.
4. Put in the Maven coordinates for the metadata client: `io.treeverse:lakefs-spark-client-301_2.12:0.1.0-SNAPSHOT`
5. Put in the repository: `https://s01.oss.sonatype.org/content/repositories/snapshots`
6. In the cluster configuration > _Configuration_ tab > _Advanced options_ > _Spark_ tab, configure the lakeFS client:
   ```
   spark.hadoop.lakefs.api.url http://<lakefs api endpoint>/api/v1/
   spark.hadoop.lakefs.api.access_key <lakefs access key>
   spark.hadoop.lakefs.api.secret_key <lakefs secret key>
   ```
7. In a Scala notebook attached to the cluster, run the following code:
   ```scala
   import io.treeverse.clients.LakeFSContext
   var df = LakeFSContext.newDF(spark, "example-repo", "your-lakefs-commit-id")
   df.show
   ```

The following error appears:
```
IllegalAccessError: tried to access field org.rocksdb.RocksObject.nativeHandle_ from class org.rocksdb.SstFileReader
```

The reason may be that Databricks has an old `rocksdb-jni` jar in the classpath.
A possible solution could be to shade the rocksdb jni in the lakeFS uber-jar, and install the uber-jar on Databricks instead of using the Maven coordinates. However, this will also be challenging since the underlying native library needs to somehow be wired to the shaded jars.

**Comment by arielshaqed** [comment]
This smells like a shading issue, but with a JNI thrown in to complicate matters.

Per https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html#library_version we may need to load different JNI versions into different ClassLoaders (the Spark hate of ClassLoaders might be striking us again).  I.e. we'd need to load parts of the RocksDB wrapper from a separate ClassLoader.

**Comment by arielshaqed** [comment]
Shading really hard here, as is dynamic loading.

https://github.com/JohnSnowLabs/spark-nlp/issues/105 might be relevant (but _really_ old).

**Comment by arielshaqed** [comment]
# Update :-(

Not really possible to shade rocksdbjni:
1. The JAR file holds its .so in the root, so it will _never_ loading the right one (Spark shared its ClassLoader with the JARs it loads, so both shaded and unshaded versions of the JAR always find the same .so, which is sad).
2. I forked rocksdbjni and made it use a .so on the package path.  Now the ClassLoader loads the shaded rocksdb which finds the right .so... and immediately fails to load the JNI, because _the C++ symbol name has to contain the full package path_ (and shading doesn't change .so's, because it doesn't know anything about binaries).

:-(

**Comment by arielshaqed** [comment]
# Proposal
We see only [rocksdbjni 6.2.2](https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni/6.2.2) on DataBricks.  If we support (only!) that version, we should be good there _and everywhere else_.

# Possible issues

1. This version is 2 years old.  It may have issues.  While on DataBricks we will be able to disavow responsibility for not upgrading, that will be harder on _other_ platforms.
1.  Some fixed bugs will still affect _all_ users, including those not on DataBricks.
1. If (when...) DataBricks issue a new version that uses some less historical version of rocksdbjni, we *will* have to split our support into two JARs.

# Fixes to rockdbjnbi after 6.2.2 filtered for relevance

These are up to 6.20.3, which is the current release.

We only read files, which makes most fixes less important.

1. Fixed a backward iteration bug with partitioned filter enabled: not including the prefix of the last key of the previous filter partition in current filter partition can cause wrong iteration result.
1. Add a new option BlockBasedTableOptions::max_auto_readahead_size. RocksDB does auto-readahead for iterators on noticing more than two reads for a table file if user doesn't provide readahead_size. The readahead starts at 8KB and doubles on every additional read upto max_auto_readahead_size and now max_auto_readahead_size can be configured dynamically as well. Found that 256 KB readahead size provides the best performance, based on experiments, for auto readahead. Experiment data is in PR #3282. If value is set 0 then no automatic prefetching will be done by rocksdb. Also changing the value will only affect files opened after the change.
1. (Possibly some fixes to checksum validation; not sure because we never read a "full" RocksDB, only single component objects.)
1. Fix a bug where compressed blocks read by MultiGet are not inserted into the compressed block cache when use_direct_reads = true.  (_Possible performance degradation, nothing worse_)
1. Fixed a bug in the following combination of features: indexes with user keys (format_version >= 3), indexes are partitioned (index_type == kTwoLevelIndexSearch), and some index partitions are pinned in memory (BlockBasedTableOptions::pin_l0_filter_and_index_blocks_in_cache). The bug could cause keys to be truncated when read from the index leading to wrong read results or other unexpected behavior.
1. Fixed a bug when indexes are partitioned (index_type == kTwoLevelIndexSearch), some index partitions are pinned in memory (BlockBasedTableOptions::pin_l0_filter_and_index_blocks_in_cache), and partitions reads could be mixed between block cache and directly from the file (e.g., with enable_index_compression == 1 and mmap_read == 1, partitions that were stored uncompressed due to poor compression ratio would be read directly from the file via mmap, while partitions that were stored compressed would be read from block cache). The bug could cause index partitions to be mistakenly considered empty during reads leading to wrong read results.
1.     An EXPERIMENTAL new Bloom alternative that saves about 30% space compared to Bloom filters, with about 3-4x construction time and similar query times is available using NewExperimentalRibbonFilterPolicy.  (_This means we will not be able to use this new Bloom alternative in Graveler..._)
1. Reduced memory copies when fetching and uncompressing compressed blocks from sst files.

**Comment by arielshaqed** [comment]
![scumbag works on code to version data for Spark; complains about Spark code versioning](https://user-images.githubusercontent.com/7802932/123950659-97d73d80-d9ac-11eb-8744-bfb29607640d.png)

**Comment by arielshaqed** [comment]
Currently it seems that we are stuck with RocksDBJNI 6.2.2, at least when running on DataBricks.

Unfortunately this runs into a _major_ problem:

## rocksdbjni 6.2.2 does not export SstFileReader to Java

Options...

### Work around it by setting up a mini-RocksDB

We can _mostly_ work our way around this.  The key is to create a new RocksDB (directory), and "ingest" the file into RocksDB.  That _usually_ requires a copy, but if we set the "move files" ingest option then there is no copy.  We *still* have to create a new DB for every file we open, which is 8 extra files totaling some 27 KiB.  Now we may iterate over this DB.

In fact we can name the DB for the metarange ID (or any similar identifier) as a first step in cache management.

#### Pros

* Uses standard existing tested code to read SSTables.
* Moderate effort on main code path

#### Cons

* Ops: ingests are inherently trickier than opens.
* Ops: need to create and manage multiple directories, each holding a RocksDB.
* Ops: moving files quickly can be tricky to set up (need to have source and dest on same POSIX filesystem)
* Have to set up some caching mechanism, with further code & ops & future development required

### Fine, I'll write my _own_ SSTable reader!

The RocksDB SSTable format that we use is documented: it's the [block-based SSTable format](https://github.com/facebook/rocksdb/wiki/Partitioned-Index-Filters#blockbasedtable-format).  And there are no merges or levels or tombstones or anything, it's a single-pass write.  Write our own JVM-based reader for a single file.

#### Pros

* Known amount of effort: essentially parse file from the end, then look up a key in a 2-level consecutive map
* No shading issues (no-one else uses it, and even when they do -- it's pure Java)
* Can rely on OS caching of blocks

#### Cons

* New code, possible surprises in the actual format on disk
* Not using existing code, which was half the point of using a standard format
* Ops: new code means novel error messages & behaviour

### Write a DynamicShadingLoader or something

Write a new `ClassLoader`.  It will load a JAR-packaged `rocksdbjni` (probably a resource JAR inside our library JAR) and expose _that_ as an appropriately shaded class.  Using some additional bytecode / reflection magic, we will be able to call routines from this JAR.  Because it will be loaded into a separate ClassLoader, we can control sharing with the Spark ClassLoader.  Probably we shall package the entire FileSystem JAR as a resource with this code, and have a single function that extracts an InputFileFormat (and some other code for export) from there.

#### Pros

* No change to existing rocksdbjni code
* Allows upgrading rocksdbjni versions
* Uses standard existing tested code to read SSTables.

#### Cons

* New area of JVM for us (me)
* Clunky build, need to put a JAR inside another JAR
* Not clear how to support export: it is not really based on an InputFileForma, so needs to be handled separately

**Comment by johnnyaug** [comment]
Great analysis!
It's a hard problem indeed.

I'm leaning towards opening an issue (epic?) for suggestion 2: developing our own SST reader (possibly by forking rocksdb?). Considering that we rely heavily on this format, it makes sense that we would want more control over the code that does the reading. Being dependent on the only Java library in the world that can read it is evidently problematic. 

That being said, this is a big effort so I think doing suggestion 1 is a good short term solution.

**Comment by itaiad200** [comment]
Had some luck using Databrick's [init scripts](https://docs.databricks.com/clusters/init-scripts.html).
The below simple script allow the export flow to continue (but flow failed because of serialization errors, see #2200 ). Hence I'm reluctant to say that using the init script will allow export to work, we should use it for debugging further issues with the Export on Databricks, and not as a workaround to enable it. 

The script uses an existing `rocksdbjni` with version `6.4.4` (same one lakeFS jar uses) that already existed on the VMs (7.6 (includes Apache Spark 3.0.1, Scala 2.12)). If we do decide to release this script as a temp solution, we should use maven install instead of relying on the package location in the VM.

```
sudo rm /databricks/jars/----workspace_spark_3_0--maven-trees--hive-2.3__hadoop-2.7--org.rocksdb--rocksdbjni--org.rocksdb__rocksdbjni__6.2.2.jar
sudo cp /dbfs/FileStore/jars/maven/org/rocksdb/rocksdbjni-6.6.4.jar /databricks/jars/rocksdbjni-6.6.4.jar
```
