### ISSUE TITLE
Explore options to link git commit and lakeFS commit

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2073]
Requested on [Slack](https://lakefs.slack.com/archives/C016726JLJW/p1623062438038300)

We support linking lakeFS commits and git commits by storing the git commit hash in the lakeFS commit metadata. That mapping is one-way and also very custom.
The goal of this issue is to come up with a mechanism that would automate this process and would also allow a git commit -> lakeFS commit mapping.

**Comment by LeonardAukea** [comment]
To further clarify. having a pointer to the specific lakeFS commits tracked by git as well would be kind of nice. This original idea as implemented by DVC would be useful even in this project.

**Comment by LeonardAukea** [comment]
I suspect doing something similar as dvc https://dvc.org/doc/command-reference/init by adding a `lakectl init` command within a git repo. This could then make sure a file is being updated as part of running `lakectl` and using SDK with the information about the lakefs repos and the current commits hashes

**Comment by mishraprafful** [comment]
Just to add more context to it, we have a very simple version of the same implemented where we are using the latest commit ID for lakeFS stored in a file called `.lakefs` that it tracked in the git. 

Essentially utilizing the branching from git, but commit capabilities from lakeFS. However, one of the big challenge here is handling merge conflicts with ease.

**Comment by mishraprafful** [comment]
### Connecting LakeFS to Git

**Use Case**
This integration is intended for users with limited Git Knowledge. Using LakeFS for data versioning leaves them at a situation of having to maintain two repositories, which is not feasible for most of the users working with Data Science. 


**Technical Explanation**

Every git repository is paralleled by a LakeFS repository for storing the data relevant to the said git repository.
A git tracked file (namely `.lakefs`) is used to store the lakefs commit. Lets's walk through a users journey to have a better understanding: 

![lakefs-git](https://user-images.githubusercontent.com/32913433/139731454-efd7db24-3f0d-4e91-aa76-d45db0e422da.png)

1. `main/master` branch on git has a `.lakefs` file with an initial commit (this is a one-time setup that should be done once a user creates a lakeFS repository, if used in a controlled setting this can be automated)
2. User forks out a new branch (say `new-branch`) on git and wishes to upload new files (or make changes to the data). The upload, list and get operations are facilitated by makefile commands as well as the python package. As soon as this, the upload command is executed: 
	1. A new branch is created from the commit SHA mentioned in the `.lakefs`file on the currently checked-out git version. (or mentioned branch, if interacting with python package).
	2. Once the branch is created, the data is uploaded to said newly created branch, the commit ID is returned back to `.lakefs` file in git. (This is committed automatically to git branch if interacting with python package)
3. User creates a PR for `main/master` branch from `new-branch` branch. 
4. If this PR gets merged on git, the latest `.lakefs` file is available on `main/master` branch.

Essentially, not utilising the branching from lakefs but only versioning with very tight integration with git branching. 

**Potential Issues**
Since the tree for lakefs is preserved all the time and the created braches are not deleted. Once a user creates the same name for multiple branches it will conflict with the existing name and will be an issue. 
As of now if the branch name exists, the change is added on top of the last commit on the branch.

**Potential Solutions**
Once a branch is merged to `main/master`on git, it should be merged on lakefs as well. But the issue with merge is that it produces a new commit, which makes the whole versioning more complicated. 

There is existing work regarding hooks with pre and post-commits, but in order to make this super generic and to satisfy our use case, if we implement a rebase for merging functionality, this would work really well. Also, the ability to choose a default option for merging strategy would be an additional cherry on the cake.

**Comment by itaiad200** [comment]
Hey @mishraprafful - the proposal looks very interesting and we had some similar ideas before. I have some questions to make sure I understand your proposal correctly:
1. What does `.lakefs` file contain? You sometime refer to the content as a commit and sometimes as a branch (which is basically a commit with a staging area you can write to).
2. It's true that merges change the `CommitID`. What about cases where they fail due to conflicts? Your code may may merge with no conflicts but data will (or vice-versa). How do you connect the 2 repos so that any operation (commit/merge/rebase/...) succeeds/fails in both repos?
3. A new `CommitID` is available only after you commit to a branch. In your proposal it seems like any upload updates the `CommitID` of the branch.

**Comment by mishraprafful** [comment]
Hey @itaiad200 
1. LakeFS file would contain the lakefs commit ID
2. That is a very difficult problem and is not really solvable in a generic manner, but for a start, if we can have the option to force override the tree with rebase of Incoming Changes, instead of a merge.
(For having traceability across both the branches, we can have (GitHub actions or GitLab CI) but these are not generic solutions, may be configured hooks can be useful here, but a merge would cause a new commit ID, which should be avoided here, using a rebase instead)
3. Maybe this was not clear on the above description, in our current implementation, every upload or change of data creates a commit. (We can change the commit ID with every commit instead of upload)

**Comment by itaiad200** [comment]
Addressing item number 3, I believe it won't work efficiently for repositories with concurrent changes to the data.
The way commit happens now, the entire branch is being locked and other commits as well as changes to data on that branch wait for completion/failure of the commit. The locking is in the database layer, so scaling lakeFS won't help here. With high volumes of changes, committing after every upload will introduce many delays and failures to commits and data changes. I don't have the exact numbers for the threshold that lakeFS can operate in this design, but given how modern ETL jobs work, uploading many files at once from several workers, I think it won't be a good user experience.

**Comment by mishraprafful** [comment]
Hi @itaiad200 I understand the concern here for having commit for every upload, But what I am suggesting is to have the integrations on commits instead of uploads, consider the following edit for the above comment. 

> **EDIT**: 2. ii. Once the branch is created, the data is uploaded to said newly created branch, and as soon as a commit is made the commit ID is returned back to .lakefs file in git. (This is committed automatically to git branch if interacting with python package)
