### ISSUE TITLE
Handle foreign repo in lakefs startup 

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2076]
Currently the following example scenario is possible. Any other combination of adapters would behave the same.
1. Starting lakeFS with a `local` block adapter settings. Creating a local repo.
2. Stopping lakeFS and starting it again with an `s3` block adapter settings.

Creating another repo is possible and all operations on it succeed (No surprise here as it was created on S3). Operations on the first repo are allowed but sometimes fail. Listing/Deleting (both metadata) work. Uploading/Downloading are allowed, but return a 500 response with the block adapter (wrong one) error.

We should either allow or disallow repos from different object stores, but decide on a way to block operations instead of returning a 500 response.

**Comment by arielshaqed** [comment]
Option (3): I am not sure why lakeFS needs to limit itself to a _single_ block adapter.  Suppose I configured a block adapter for each repo (like I configure storage namespaces). What would fail?

1. Pyramid / tierFS _works_, because metarange and range objects are per-repo.  So naturally lakeFS can store them on the repo's block adapter.
2. Thick clients would (_obviously!_) have to support each configured block adapter...
3. We'd have to name block adapters somehow to be able to distinguish multiple adapters of the same type.

If this is a requirement... why not?

**Comment by itaiad200** [comment]
I tend to agree here. Adding to point#1 is actions/runs which are also per repo.
We would also need to change the way we collect the metrics if multiple adapters are allowed.

This wasn't a requirement up until now. Given how delicate this change would be and that it isn't an external requirement, I suggest we first improve our current UX with the single block adapter and foreign repos.
