### ISSUE TITLE
Branch reference with explicit workspace - reference committed or uncommitted

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#2135]
The branch URI support referencing a specific workspace - committed or the uncommitted (stage).

1. Uncommitted - `lakefs://repo/branch#` or `lakefs://repo/branch#/file.txt`
2. Committed (last commit / HEAD) - `lakefs://repo/branch@` or `lakefs://repo/branch@/file.txt`
3. Non-explicit - `lakefs://repo/branch`

Non-explicit branch references will work on the committed/uncommitted environment based on the operation.
For example:
- list, get and put objects works on uncommitted.
- merge target branch will work on committed, as there is no meaning in specifying the committed area of the branch as a target.

**Comment by ozkatz** [comment]
I think we need a more explicit language for handling this type of notation
In lieu of a "Reflog", I suggest borrowing the syntax used for that in Git.

following your example it could be something like this: `lakefs://repo/branch@{modifier}/file.txt`

So for the current commit it'll be `lakefs://repo/branch@{committed}/file.txt`

To show staged changes, do: `lakefs://repo/branch@{staging}/file.txt`

---

This explicitness would allow us to remain flexible enough to accommodate future changes that *might* be desireable,
for example, supporting multiple staging tokens (or multiple change-sets of any sort), one could then do: `lakefs://repo/branch@{staging:<staging token ID>}/file.txt` - Or extend it further to support bitemporality a-la: `lakefs://repo/branch@{as-of:2020-01-01}/file.txt`.

Of course, none of these are a requirement **right now**, but of all possible breaking changes we might end up doing, [breaking URIs are the worst change to make](https://www.w3.org/Provider/Style/URI) (This link is currently broken, which is irony at its best).

CC'ing people I know will hate this proposal: @itaiad200 @johnnyaug @arielshaqed :)

**Comment by arielshaqed** [comment]
> The branch URI support referencing a specific workspace - committed or the uncommitted (stage).
> 
>     1. Uncommitted - `lakefs://repo/branch#` or `lakefs://repo/branch#/file.txt`

Not a fan: `#` _does_ appear to work in all shells, but AFAICT it might end up being special in URLs.  This is not a huge objection because the user can _and should_ always `%23` their way out of trouble... but it is a bit less convenient.

> 
>     2. Committed (last commit / HEAD) - `lakefs://repo/branch@` or `lakefs://repo/branch@/file.txt`

This is exactly compatible with the way that Git uses `@`, so obviously good!  (We can add more `@` meanings later if desired, e.g. Oz does just that...).

> 
>     3. Non-explicit - `lakefs://repo/branch`
> 
> 
> Non-explicit branch references will work on the committed/uncommitted environment based on the operation.
> For example:
> 
>     * list, get and put objects works on uncommitted.
> 
>     * merge target branch will work on committed, as there is no meaning in specifying the committed area of the branch as a target.

* Not all operations support non-explicit branch references everywhere.

**Comment by johnnyaug** [comment]
@ozkatz as a user, I wouldn't be happy to use a syntax that includes a modifier in curlies. I wasn't aware that git had such a syntax so it's probably not in their critical path. 

I want to make a little distinction between when we use a branch name as a ref and when we use it as branch name. I suggest that when using it as a branch name, it is irrelevant to specify any modifier. Examples: put operation destination, merge destination. 
 
With that in mind, I argue that we only need one type of modifier, which is for the uncommitted/staging. We can use `@` as @nopcoder suggested. This will also be forward-compatible with future modifiers similar to what Oz suggested.

How it will work:
GET/LIST/DIFF can take the committed by default. The modifier can be added to get the staging.
PUT: as mentioned above, modifiers are irrelevant here IMO: the branch passed to a Put operation is not a ref, but rather a branch name.
MERGE source: should always ignore staging (IMO you could argue otherwise).
MERGE destination: not a ref, as mentioned above.

**Comment by nopcoder** [comment]
The branch explicit reference to stage/last-commit environment will be relevant for all locations we pass a `ref` (like path or diff source/target).
Operations where we need to specify a branch name - ex: create or delete branch will use only the non-explicit format.

Defaults:
MERGE operation destination can only be a non-explicit branch name. the source can be branch name or the last-committed, as it behaves like any other ref.
PUT can only be a non-explicit branch name (like merge destination) there is no point it doesn't accept ref.
GET/LIST - the default is uncommitted. we should keep the same behavior as today.
DIFF - can diff between any ref. we can use explicit branch references.
  The defaults here are a bit tricky as if you going to do a merge you like to diff between the two latest-committed. If you like to see what changed you want to check only the latest uncommitted.
  Think we can keep the current behavior and compare by default (branch name) the committed information. but have in the UI we should add another branch selection - labeled workspace/uncommitted.

**Comment by itaiad200** [comment]
@nopcoder Did you intend to close this one? I thought #2178 was just splitting the references, not applying the default ref logic just yet.

**Comment by nopcoder** [comment]
@itaiad200 right, reopen - needed to link and not reference `close` by the pr.
