### ISSUE TITLE
Configure JAR assembly shading using exclusions rather than inclusions

### ISSUE THREAD

**Issue by ozkatz** [treeverse/lakeFS#2160]

**Comment by arielshaqed** [comment]
Our shaded JARs always _include_ libraries into shading.  And we keep on having to increase the scope of included shadings.  Investigate whether we would be better to _exclude_ libraries from shading.  That would make shading configuration more like the definition of the Spark <-> library API: the non-shaded objects are an exact superset of the objects which we intend to share across the API.

**Comment by arielshaqed** [comment]
I tried it out by going over all of our dependencies.  This idea turns out not to be an improvement.  Specifically, these two types of dependencies end up the same regardless of inclusion or exclusion, so they require the same analysis:
* _Trivial_ dependencies: anything that is not likely to be shared, or that is a direct dependency, or that clearly has no objects passing between Spark-provided and Treeverse-provided libraries.  The only hard bit is concluding that they are trivial.
* *Difficult* dependencies: anything that requires careful analysis, like protocol buffers or various commons libraries and **especially** distant dependencies, such as `com.sun.jersey`.  They stick around for a long while, and are never easy to decipher or decide about.

Closing as I didn't see an improvement while trying it out.  To be fair, I didn't see anything worse, either; it'll just be repeating the same work we've already done in the other direction.  So for now no point in proceeding.
