### ISSUE TITLE
Make ListingIterator include LakeFSFileStatus instead of LakeFSLocatedFileStatus

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2239]
This issue is a follow-up task to #2237. 

ListingIterator was implemented to make `LakeFSFileSystem.listFiles` return RemoteIterator<LocatedFileStatus>. therefore, ListingIterator has to do with LakeFSLocatedFileStatus. It also used by multiple LakeFSFileSystem operations to identify whether a path represents a directory (lakeFS's common prefix). 

To avoid bugs similar to #2237, we would like to make the default listing capability return LakeFSFileStatus by default and convert it LakeFSLocatedFileStatus when there is a need.

**Comment by arielshaqed** [comment]
As discussed F2F, I am unsure of this.  To be very clear: the fact that Databricks behaves differently with LakeFSFS for `FileStatus` and its derived class `LocatedFileStatus`  is a bug, either in DB or in LFSFS.  If LFSFS is returning a correct `LocatedFileStatus` then it's a bug in DB; otherwise, if we believe that DB is correct then _by definition_ it's a bug that LFSFS doesn't follow the class hierarchy spec.  The only reason we need to discuss and this bug is not clear is that there is no documentation for the `FileStatus` spec.

We have these options:
1. Declare that LocatedFileStatus.Location is non-nullable.  Then we had a bug in LFSFS, and you fixed it, and we're done.  Cool!
1. Declare that DB (maybe with other parts of the Spark ecosystem) has a bug, and in order to work around it we cannot allow ourselves to return `LocatedFileStatus`.

I much prefer the first option, i.e. to close this bug and declare that we were previously at fault, but that DB / other Spark had no bug here *except* in not documenting any fields anywhere.
