### ISSUE TITLE
Non-descriptive error message while trying to create an Admin user more than once 

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#2307]
### Description 
When a user tries to create an Admin user on a lakeFS setup that already has an Admin user, a non-descriptive error message is shown in the UI ("Conflict"). 
We should change the message to report the actual error, the message could be "Admin user already exists".

![Screen Shot 2021-07-29 at 9 24 04](https://user-images.githubusercontent.com/14786381/127442219-cb2401a2-9841-4d31-8a5c-921149fc4f5d.png)

### Steps to reproduce
1. Setup lakeFS or use an already existing setup
2. go to https://lakefs.domain/setup
3. Type in a username and click setup

**Comment by DataDavD** [comment]
I'm not sure if anyone is currently working on this, but if not I would be happy to take it up.

**Comment by talSofer** [comment]
Hi @DataDavD, Thanks for being an active community member!

@lynnro314 is currently working on this issue. You are welcome to choose another issue you would like to work on, if you pick an issue that doesn't have asignees, the chances that no one started working on it are higher. Let us know the issue you chose and we will confirm that no one started working on it :)

**Comment by DataDavD** [comment]
Thank you for the quick, detailed response @talSofer. sounds good!

I asked on a couple other low activity/empty `good first issue ` issues actually so I'll look there too.

Thanks again.

Best, 
dd

**Comment by DataDavD** [comment]
hey @talSofer FYI. I may get to this later than I originally anticipated as I'm only really just now getting started with https://github.com/treeverse/lakeFS/issues/2415#issuecomment-930441069 (had some work/life issues that took up a large part of time last couple weeks).  I'm happy to still work on this once I'm done with the other issue, but I just wanted to give you an update, just in case some knows/wants to work on this now/ASAP.

In the meantime, I'm still going to give this a more thorough look tonight since the last time I looked at the code for this issue a couple weeks ago I couldn't directly make how where the change should be centered. If I have more question I'll post those here as well as the lakeFS slack server. 

Thanks again for all y'alls help

Best,
David

**Comment by talSofer** [comment]
Hi @DataDavD ! thanks for keeping me posted! 
This issue was already resolved by @lynnro314 so no further action is needed here. Thanks again.

**Comment by DataDavD** [comment]
hey @talSofer thanks for update. I mistakenly thought I was making a comment on this issue https://github.com/treeverse/lakeFS/issues/2316#issuecomment-910048659 🤦 . Sorry about that.
