### ISSUE TITLE
SSL Certificate Variable for lakectl

### ISSUE THREAD

**Issue by tvanderwal-lmco** [treeverse/lakeFS#2421]
Currently when trying to use `lakectl` with a custom SSL certificate it throws a "x509 certificate signed by unknown authority" error. In slack I did get a workaround to add the certificate into my Mac's key chain, however it would be nice to also be able to set an environmental variable that the `lakectl` utility would respect. 

A few reasons would be 
1.   Our enterprise users don't generally have admin rights on their computers to do the workaround
2. Standardizes the setup for users on differing operating systems
3. Follows the same pattern as other cli tools, such as `awscli`, `pip`, and `kubectl`. 

In general I've seen most applications just accept `SSL_CERT_FILE` but it's not uncommon to have application specific ones if you so choose.

**Comment by arielshaqed** [comment]
Ouch!  This is an issue with the Go crypto packages.  Specifically if you [search for `SSL_CERT_DIR`](https://github.com/golang/go/search?q=SSL_CERT_DIR&type=code) you see that they _explicitly_ seem to limit this variable to non-MacOS UN*X-like systems.

I am not sure why, AFAICT (and AFAIR) OpenSSL _always_ accepts these environment variables, as documented e.g. in [the documentation of `SSL_CTX_load_verify_locations`](https://www.openssl.org/docs/man1.1.0/man3/SSL_CTX_set_default_verify_paths.html).

So when doing this, we must be _very_ careful not to break the current default behaviour of Golang crypto on MacOS and Windows (which is expected), while also not breaking the expectations of people who expect OpenSSL semantics.

**Comment by arielshaqed** [comment]
Thanks for the bug report!

I am (regretfully) closing this issue, here's why.

I spent a bit of time going down the trusted CAs rabbit hole.  As feared, golang/go#37907 (aka https://github.com/golang/go/issues/37907) ("crypto/x509: documentation about SSL_CERT_FILE and SSL_CERT_DIR is incorrect" [on macOS]) was explicitly closed by documenting the fact that macOS ignores these variables.

## Options

To be clear: we shall not have a good solution on macOS.  There are (at least) two conflicting keychains in play: the macOS keychain and the OpenSSL-inspired "keychain".  golang chooses to use the macOS keychain, and it is more secure and better integrated.  The OpenSSL-style configuration is less secure (less control over how CAs become trusted).

## No good solutions

Both solutions _will be confusing_:

* Our current "go with golang" solution means that UN*X users on macOS are going to be confused.
* The alternative "go with OpenSSL" solution (support OpenSSL envariables) would mean that macOS users _and_ users who have configured their golang environment correctly are going to be confused.

Closing (with regrets) as I prefer to go with the platform rather than with the custom.  macOS is increasingly a separate platform, like Windows, and applications should play to its strengths.  In particular it is reasonable for users to assume that applications will not undermine its security.

**Comment by arielshaqed** [comment]
About this issue:

> 1. Our enterprise users don't generally have admin rights on their computers to do the workaround

I am not a macOS user, but AFAIU every user should have a _login keychain_ intended exactly for this purpose, e.g. https://support.apple.com/en-il/guide/keychain-access/kyca2431/mac.  Can your enterprise users add this trusted cert to _that_ keychain?  It should _not_ require admin access to modify.
