### ISSUE TITLE
Call out "history-retaining merkle tree" more prominently, pls

### ISSUE THREAD

**Issue by paul-hammant** [treeverse/lakeFS#2459]

**Comment by talSofer** [comment]
Hi @paul-hammant, thanks for opening this issue! 
Would you kindly provide more context to this ask? (I guess it's related to the documentation or our system internal but will appreciate more details)

**Comment by paul-hammant** [comment]
Elsewhere in the repo's issues/commits etc there is talk of merkle-trees as an important design factor for your tech. You've not called it out on the README and perhaps should do.

https://aws.amazon.com/qldb/ implements merkle-tree aspects. Though as I check now, the blurb they have no longer lists that as a selling point :(

**Comment by talSofer** [comment]
Thanks @paul-hammant!

Did you get a chance to read through https://docs.lakefs.io/understand/data-model.html? in particular through https://docs.lakefs.io/understand/data-model.html#constructing-a-consistent-view-of-the-keyspace-ie-a-commit? 
Let me know if this is what you were expecting to see. 

It is an (important) implementation detail, therefore I believe that adding it to the README may be a bit distracting, but our docs should definitely include this.

**Comment by arielshaqed** [comment]
Hi @paul-hammant !

Thanks for the suggestion!  I'm going to ramble on for a bit to explain my motivations, then ask a concrete question (I promise!).

AFAICT we primary refer to Merkle trees on our [Data Model page, "Constructing a consistent view of the keyspace"](https://github.com/treeverse/lakeFS/blob/70275211c77c454bbb5e3fd120744b3703f953e8/docs/understand/data-model.md#constructing-a-consistent-view-of-the-keyspace-ie-a-commit).  And this is of course a core implementation detail.  It appears in @ozkatz 's  design doc that transmogrified into the "Data Model" page above, and less formally I've [blogged](https://lakefs.io/concrete-graveler-committing-data-to-pebbledb-sstables/#h-introduction) about it ([twice](https://lakefs.io/concrete-graveler-splitting-for-reuse/)).

As an open-source project, our documentation has to reach two distinct audiences:

* Our _users_ are  primarily interested in the git-level abstraction that lakeFS provides for managing their data.
   Like any other Git user, they care mostly about porcelain, and less about the plumbing.  Ideally these abstractions should be enough for them to be able to ignore entirely the implementation, even headlines such as "Merkle tree".  But I believe that we should aim to allow them to be happily oblivious of the design.  This is similar to how Git should be usable without reading the [Git Internals](https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain) chapter, at least not beyond "plumbing and porcelain.
* Our _developers_ (and our "tinkerers" and our "curious users") may need to understand the design at the lower levels.  Even then, we try to keep the "Graveler" abstraction wall to allow developers (ourselves included) to ignore its details when working outside of it.
   We keep the data model documentation and informal descriptions in order to help our developers (ourselves included) in the loop.  Currently we do not have a "lakeFS Internals" chapter in our documentation.  Indeed, we try to stand on the shoulders of giants and are happy to use terms such as "Merkle", "git"[-like], "SSTable", and "B+Tree".  

I would categorize this issue that you have opened as increasing the level of documentation for our developers.  Do you agree?  Where do you imagine seeing this added description, and at what level -- more annotation on its current mention, a new section, a references / further reading chapter in the data model, somewhere better perhaps?

Thanks!

**Comment by paul-hammant** [comment]
I am happy that y'all have duly considered it and designated the fact that the tech uses Merkle trees to be an internal detail. I guess git does too: There's no explicit git verify-merkle-tree operation over a clone to a FS. Git does that silently and would blow up if something in a clone didn't add up.
