### ISSUE TITLE
Temporary TRACE logging

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#2791]
It's sometimes hard to change your configuration settings to allow TRACE logs for debugging an issue. Also, it will always follow by another change to reduce the verbosity of the lakeFS instances, since it's not sustainable for long periods for some installations. It would be best if there's an easy method of doing that without changing configurations and restarting the instances.

Some possible directions:
1. “Toggle trace for the next X hours/days” - That it will toggle it on and off automatically, without having to “maintain” or remember to do it. 
1. Adding an header to the request that will increase the verbosity of that request and that request only.

**Comment by arielshaqed** [comment]
Can we grab such functionality from an existing project?  I am unfamiliar with the common controls are for doing this sort of log-level changes.

I like alternative (2): if a request arrives with an `X-Trace-Whatever` header set (_and_ if the user has appropriate permissions, to prevent flooding), we set a verbose bit on the context -- and log more.  I've used this one to great effect at previous places of employment.  However it can be difficult to set for users who are using higher-level pipelines.

Similar to alternative (2): trace 1 in 2000 (or whatever) requests.  This requires less configuration but is only relevant for common failures -- otherwise you don't get a failure for the one request you do care about.
