### ISSUE TITLE
lakectl ingest from Minio

### ISSUE THREAD

**Issue by slumbi** [treeverse/lakeFS#2886]
Is it possible to use `lakectl ingest ` to get data from minio instead of amazon s3 ?

**Comment by johnnyaug** [comment]
@slumbi, thank you for opening this issue. This is currently not supported. We will consider prioritizing it.

**Comment by tshradheya** [comment]
@johnnyaug I would like to work on this issue if no one has picked it up yet?

**Comment by johnnyaug** [comment]
Hey @tshradheya, sure!

**Comment by tshradheya** [comment]
@johnnyaug i couldnt find any documentation on how to build to generate `lakectl` command after making changed to the code repo.
Could you guide me on that so I can test out my changes

**Comment by arielshaqed** [comment]
Happy with #3084 and it _will_ close this issue!

**Future readers** please note well: ingesting will only ever work when lakeFS uses the same storage as the ingest command.  So that PR closes this, and you can ingest existing files on your MinIO into your lakeFS instance that uses that same MinIO.  You will still *NOT* be able to "ingest" from MinIO to AWS S3, because ingesting does not copy... use rclone or distcp for that.
