### ISSUE TITLE
hive-ms: merge meta data

### ISSUE THREAD

**Issue by chaimt** [treeverse/lakeFS#2930]
after branch has been merged to master, if schema was changed we need a way to merge the changes from the branch hive-ms to master hive-ms

**Comment by Jonathan-Rosenberg** [comment]
Hey @chaimt,
Thank you for opening this issue!
In order to further understand the issue it would be very helpful if you'll share with us what you would expect to get merged as a result of the merge process. 
If you can also share a diff between schemas, and a desired result that would be awesome!

Thanks!
