### ISSUE TITLE
Change output on user/group creation with exists user id on lakectl

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#2974]
When trying to create a user (`lakectl auth users create`) with a user id that's already exists we get "query INSERT INTO auth_users (display_name, created_at, friendly_name, source) VALUES ($1, $2, $3, $4) RETURNING id: scany: rows final error: ERROR: duplicate key value violates unique constraint "auth_users_unique_display_name" (SQLSTATE 23505)"
We want to change the output in this case to more user-friendly text.

**Comment by N-o-Z** [comment]
2 suggested options to fix this issue:
1. Simple: directly in authUsersCreate lambda - catch response before DieOnErrorOrUnexpectedStatusCode and parse it - if it contains the relevant string - issue a specific error message and die.
This solution is straightforward but is not systemic and will not provide a solution for other errors / commands
2. Modify ResponseAsError, add a dictionary of known response messages (regex / or substr) and corresponding error messages and check if response message is a match. If so issue the required error message otherwise fallback to the response message.
It is also possible to use the request data inside the response to better select the appropriate error message

**Comment by arielshaqed** [comment]
I would rather that lakeFS (the server) return an appropriate error.  Otherwise _every client_ has to understand PostgreSQL...

We can do this by detecting conflicts: analyze the error return (look for an error of type `PgError`) and then you can see the PostgreSQL error code.  In code terms, I'd put a function `IsConflict` that does that in `package db`, and then analyze the return values for INSERTs in `auth` to see whether they are conflicts.

WDYT?

**Comment by arielshaqed** [comment]
> [...]
> The downside is that we will have to create a specific case for each DB error we want to wrap with a human readable error message. The suggestion to check this in the auth package for INSERT operations seems a bit more patchy IMHO

You're (very) right!  Digging into it a bit more, I think that the bug you uncovered is actually one layer deeper (and I think it's my bug)!  We have `db.ErrAlreadyExists` that does exactly what we both want.  But only `Tx.Exec` returns it.  We never get it because `Tx.Query` and the other routines never return it.  We shuld extract the error rewriting logic from this and other functions, and do all error handling together.

WDYT?

**Comment by N-o-Z** [comment]
I'm not a DB expert but if you think it's good to consolidate error handling for all the Tx interfaces then it sounds like a good idea.
One thing that remains open is the http status returned from the server itself. I'm not sure 500 (InternalServerError) is an appropriate status for DB operations errors.  Should we return BadRequest instead?

**Comment by arielshaqed** [comment]
> I'm not a DB expert but if you think it's good to consolidate error handling for all the Tx interfaces then it sounds like a good idea.

Not a DB expert either, but: it's an obvious bug for any client of `package db` to access PostgreSQL error codes.  So we need to return appropriate errors from this package (even if they're just re-exports of the PostgreSQL codes).  No package outside of `db` should `import "jackc/pgx/..."` or the like.

> One thing that remains open is the http status returned from the server itself. I'm not sure 500 (InternalServerError) is an appropriate status for DB operations errors. Should we return BadRequest instead?

I think that you are correct -- it looks like a client error, so some 4xx would be warranted here.  Also that makes clients easier to write :-)

**Comment by N-o-Z** [comment]
What I meant was, if it is good practice to create a general error handling flow which will be used by all interfaces.
But I think we have most of it figured out - maybe take a deeper look on the PR itself, thanks!
