### ISSUE TITLE
Skipped hooks should be visible in the Action Run view

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#3098]
When some hook fails during an Action Run, the next hooks are not executed.
The view should explicitly mention the those hooks were skipped. Currently, the view simply doesn't display them.

**Comment by tshradheya** [comment]
If no one has taken this yet, I would like to work on it :)

**Comment by itaiad200** [comment]
All yours @tshradheya .
To understand more about hooks, check out our [docs](https://docs.lakefs.io/setup/hooks.html)
For code references see this [package](https://github.com/treeverse/lakeFS/tree/master/pkg/actions), [this](https://github.com/treeverse/lakeFS/blob/5b7547c5606120bb1869bc5ab03eecd2555e1157/pkg/actions/service.go#L212) is where the hooks are skipped.

**Comment by tshradheya** [comment]
Sorry for the delay on getting started on this. From the code I see that currently it only supports two statuses `failed` and `passed`.

For a CI usually two other statuses are possible `waiting` (since done in sequence in our case it just lists future steps) and `skipped` (when one fails and we dont run the future.

From my understanding `waiting` is not a possible scenario cause we only save run status into DB after the complete Action is run. @itaiad200 could you confirm this?

And this story is to support `skipped` so that we can show the user which are the future Hooks for that Action.

**Comment by itaiad200** [comment]
@tshradheya , I can confirm that. We'll have better support for `skipped` & `waiting` actions while we implement #3020 , which will allow long running actions, so a DB representation of it is a prerequisite.

#3359 looks like a good implementation given that constraint, I'm in favor of supporting `skipped` hooks before we complete the long running hooks task.
