### ISSUE TITLE
Add test connection functionality to the API

### ISSUE THREAD

**Issue by eden-ohana** [treeverse/lakeFS#3125]
Add operation that checks whether there is permission to list or write to a given storage namespace.
will be used on:
* lakectl ingest through the UI, check if there is permission to the bucket to ingest from
* when setting a new storage namespace on the UI when creating a repo, add test connection button that will test the permission to the path, if permission is denied will provide a snippet to add to s3 configuration to allow lakefs the permissions.

**Comment by itaiad200** [comment]
@eden-ohana @ozkatz I don't understand why this check needs its own API.
lakeFS would still have to check before `createRepo` or `ingest` that it is able to perform operations on the given storage path. The `Test Connectivity` would just repeat this check and return similar error. It's not actionable (i.e. lakeFS can't "know" if it failed due to lack of permission to lakeFS, missing credentials, missing bucket policy, etc.), other than linking to some doc explaining what are the required permissions. We need to wrap the `could not access storage namespace` (or similar ingest error) message and make it friendlier. Another check-connectivity API would be checking a subset of possible errors - without new actionable information.
