### ISSUE TITLE
API to support new functionality of import from the UI

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#3150]
Part of https://github.com/treeverse/lakeFS/issues/3137

API needs to open new endpoints specified in #3137. 
It also requires to list objects from the object store and pass them to graveler.

**Comment by arielshaqed** [comment]
# ⚠️ May have security impact ⚠️ 

I think this may have a severe impact on security.  

This allows an unprivileged user to *read and **list** * objects wherever lakeFS has permissions.  As such it may make configuring lakeFS safely almost impossible.  It will certainly add some surprising gotcha's to secure configuration.

The following scenarios are ordered by increasing severity, because each relies on the previous one to make things even worse.

## Users can list (and read) any file that lakeFS can list and read

Previously users could only read a file if they knew its name (simply by ingesting it).  With this feature, I can ask to import `s3://bigcorp/secrets/` into `lakefs://my-repo/main/harmless/` and read any file under `secrets`, _without knowing its name or even that it exists`.

You might say "OK, so I will limit the lakeFS role only to read and write under `s3://bigcorp-lakefs/repos/`!"  So let's go up a notch...

## Users can list (and read) any file stored on lakeFS

With this feature, I can ask to import `s3://bigcorp-lakefs/repos/secret-repo-namespace` into `lakefs://my-repo/main/mostly-harmless/`.  Now I can read lakeFS metaranges and ranges of `secret-repo` to discover filenames and their paths in `secret-repo-namespace`, and then read underlying objects.  This completely overrides lakeFS IAM settings for reading data.

You might say "well, but it's gonna be a lot of work!"  And it would be really annoying.  So let's put a nice interface on top of it...

## Users can use a second lakeFS to list (and read) any file stored on lakeFS :-)

Instead of reading metaranges and ranges with nasty CLI tools, I can use the world's greatest tool for reading them!  I start a _second_ lakeFS.  This one uses the S3 block adapter pointed at the S3 gateway endpoint of the first lakeFS.  Now I can create a repo `lakefs://great-gui/` with storage namespace `s3://my-repo/main/mostly-harmless/`.  I will need to reset the HEAD of branch `main` at some metarange (maybe pick the metarange that was written last; that's gonna be _some_ recently-modified HEAD!), and now `lakefs://great-gui/main` on the second repo gives comfortable (but read-only...) access to `lakefs://secret-repo` on the first repo.

# Recommendation

Unfortunately the only ways around this make the feature *very* scary to use.  Basically you will need to add a new permission (similar to the one for storage namespaces) that gets used for import.  And you will need to make it very clear to administrators that they cannot simply hand out this permission.

1. Add special a special lakeFS IAM role that allows importing only from specific paths.  Have it disabled by default for all users except administrators.
1. Document extensively the security considerations for using this feature.
1. Warn about the security implications in the GUI before importing.

**Comment by itaiad200** [comment]
That's a great input. I think the same concerns exist today with `lakectl import`, although it's harder for a less-privileged user to run lakeFS binary.

**Comment by nopcoder** [comment]
The same concern is true for the stage API. Having arn for external resources - will match on physical address.

**Comment by arielshaqed** [comment]
> The same concern is true for the stage API. Having arn for external resources - will match on physical address.

Of course! However (AFAIK) you need to know the path to read an object - lakeFS itself should have no permissions to list.
AFAIK, the second and third abuse-cases I give above (total bypass of iam read permissions) are impossible to achieve with the staging api.

**Comment by arielshaqed** [comment]
> The same concern is true for the stage API. Having arn for external resources - will match on physical address.

Of course! However (AFAIK) you need to know the path to read an object - lakeFS itself should have no permissions to list.
AFAIK, the second and third abuse-cases I give above (total bypass of iam read permissions) are impossible to achieve with the staging api.

**Comment by arielshaqed** [comment]
## Suggestion

How can we support this safely?  We might try to extend what we did with the action `fs:AttachStorageNamespace` that takes `arn:lakefs:fs:::namespace/{storageNamespace}`, where `storageNamespace` looks like `s3://bucket-on-aws-s3/allowed/here`.

To do that:
* Add a new IAM action `fs:import`.
* Use ARN `arn:lakefs:fs:::storage/{prefix}`.
* Verify on the import API that the user is allowed to import from that prefix.

## Pros

This allows safe configuration.  It extends _what we already do_ when creating a repo -- so not introducing anything new or unacceptable to our users.

## Cons

Misconfiguration here is much worse than with "create repo": as outlined in the issue description, a user allowed import can *discover* and read any file accessible by lakeFS: in particular, since lakeFS [has permissions to list and read its own bucket](https://docs.lakefs.io/setup/storage/s3.html), if we do not limit users then they can bypass all lakeFS IAM read protection.

So we need to block (regular) users by default from accessing various parts, maybe even not allow them to import.  But obviously the point of the feature is to make import quick and easy.

So **by default** we could allow this only for admins -- the initial user is an admin, so import would be easy there.
