### ISSUE TITLE
KV model support functionality

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#3240]
Support code that enable working with serialized data model from protobuf to the KV library

**Comment by N-o-Z** [comment]
I want to suggest alternatives for using protobuf.
I did some research and came with the following viable alternatives:

1. BSON https://bsonspec.org/ (Binary JSON)
    - Advantages:
      - Ordered
      - Traverse-able
      - Smaller than JSON
      - Quick to encode decode
      - Supported by many languages (uses C data types) https://bsonspec.org/implementations.html
      - Has a built go mongo driver
    - Disadvantages:
      - Slower than protobuf
      - Requires importing the specific implementation package
      - Last update 2015?
14. https://msgpack.org/ (another binary json)
      - Same properties as BSON - seems more maintained
      - Limited in data type sizes (for example max str size 32B)
17. Flatbuffers https://google.github.io/flatbuffers/
      - Advantages:
        - supports a variety of languages
        - Developed by google
        - No additional memory to access data
        - Access data without parsing / unpacking
        - Supports optional fields
        - Last release May2020
        - Supports schema-less version
     - Disadvantages:
       - Requires schema compilation from C++

My tendency is to go with Flatbuffers as it is very memory efficient both in storing and accessing data and very fast (doesn't require unpacking of data)

**Comment by itaiad200** [comment]
Thanks @N-o-Z , it made me smarter :)
I wonder how would the above protocol characteristics map into solving the challenges we arose before (copying our summary for the discussion on this topic):
```
KV Value Format aspects for comparison:
- Data readability
- Should we use ID together with the value?
	- Application level: Can customize the fields for computing the id (e.g. timestamp)
	- DB level: Just like graveler. DB can leverage it to use a shorter field for SetIf
- Backward compatibility
- protobuf has metadata, json doesn't
- Compression; size of deserialised objects
- Popularity of format
```

**Comment by N-o-Z** [comment]
@itaiad200 answers for flatbuffers regarding the issues you've raised:
- Data readability - same as protobuf, the binary format doesn't allow as to read the data as is, but different from protobuf the data can be read without de-serialization if you are familiar with the data structure (or via the object file)
- Supports optionals and defaults so we should be fine with backwards compatibility
- Not needed as it is structured (with a caveat here)
- Compression - we will see that in the benchmarking I made the binary size created by flatbuffers is bigger than protobuff, on the other hand there's no need to de-serialize the data when using flatbuffers
- The format was created and maintained by google for the gaming industry and is used by Facebook among others

**Comment by N-o-Z** [comment]
As stated previously I performed a benchmark test comparing flatbuffers and protobuf, measuring, speed, memory allocation and binary size.
The test scenario was done using data set taken from the multipart module and includes a map field which is not modelled in flatbuffers (yet?) and requires implementation via a separate table (which incurs an overhead).

**Summary:**
We can see in the results that binary size after serialization of data is bigger in flatbuffers than protobuff which is expected.
On the other hand when running a single iteration we can also observe that there was more memory allocations using protobuf vs flatbuffers. I assume this is due to the unmarshelling process
Finally, we can see that when benchmarking the flatbuffers scenario vs the protobuff there's a more than 3x perfomance improvement

Test code: https://github.com/treeverse/lakeFS/tree/flatbuffers_benchmark

**Results:**

Running a single iteration to check memory allocations:

```
go test -bench=. -benchmem -benchtime=1x
goos: linux
goarch: amd64
pkg: github.com/treeverse/lakefs/pkg/gateway/multiparts
cpu: 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
BenchmarkFlatBuffer-16    	1000000000	         0.0000221 ns/op

BenchmarkFlatBuffer-16     	       1	      7367 ns/op	     872 B/op	      16 allocs/op
Buffer size:  224

BenchmarkProtoBuffer-16    	       1	     20324 ns/op	    1448 B/op	      35 allocs/op
Buffer size:  107
```
Running 1000000000 iterations we can see a significant performance difference:

```
go test -bench=.
goos: linux
goarch: amd64
pkg: github.com/treeverse/lakefs/pkg/gateway/multiparts
cpu: 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
BenchmarkFlatBuffer-16     	1000000000	         0.0000036 ns/op
BenchmarkProtoBuffer-16    	1000000000	         0.0000126 ns/op
```

**Comment by N-o-Z** [comment]
Decision: Reviewed pros and cons in an internal discussion, decided to continue development using protobuf, as it is a format already used in lakeFS and has a smaller binary (which affects the read time from the database)
