### ISSUE TITLE
RouterFS: Support lakeFS via S3 gateway

### ISSUE THREAD

**Issue by Jonathan-Rosenberg** [treeverse/lakeFS#3327]
As a first step, support lakeFS usage via the S3 gateway only. That means that the following configuration should work seamlessly:

```properties
fs.s3a.impl=RouterFileSystem
routerfs.mapping.s3a.1.replace=s3a://bucket/dir1/
routerfs.mapping.s3a.1.with=lakefs://repo/main/
fs.lakefs.impl=LakeFSFS
fs.s3a.access.key=<lakeFS access key>
fs.s3a.secret.key=<lakeFS access secret>
fs.s3a.endpoint=https://lakefs.example.com/routerfs
fs.s3a.path.style.access=true

routerfs.default.fs.s3a=S3AFileSystem # To handle other not lakeFS supported s3a URI paths
```
Parent issue: #2625

**Comment by arielshaqed** [comment]
Not sure about this line:
```properties
fs.lakefs.impl=S3AFileSystem
```

Also, we should support and test routing between (at least) **TWO** different S3A backends.  I would suggest S3 and MinIO, but any 2 really -- we could test with two MinIO instances.

**Comment by Jonathan-Rosenberg** [comment]
@arielshaqed why not sure about that line? Don't we want to test the redirection of given backends to lakeFS using the S3 gateway? If we won't configure the FileSystem class implementation to use with the `lakefs` scheme, how would Spark know what to do with it?

Regarding the multiple backends, yes I didn't mention it. Will correct the description.

**Comment by arielshaqed** [comment]
Sorry for lack of clarity.

> @arielshaqed why not sure about that line? Don't we want to test the redirection of given backends to lakeFS using the S3 gateway? If we won't configure the FileSystem class implementation to use with the `lakefs` scheme, how would Spark know what to do with it?

I am all for this test, I just would not call it "lakefs" in the basic example.  You can use this filesystem independently of lakefs, and I believe it is _easier_ to understand it as a separate component.

> Regarding the multiple backends, didn't quite understand. Are you referring to the "from" or the "to" part?

"To".  I would like to have 2 non-default mappings, to different S3 backends, in addition to a default mapping -- which might share the same backend but with different prefix mapping.

Also it occurs to me: did we decide not to support regex in "from"?  Otherwise you should probably start each pattern with `^`.
