### ISSUE TITLE
Evict user from the auth cache once a user reset his password

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#3404]
The problem: when a user logs in to lakeFS we save his credentials in the auth-cache. This way, we avoid authenticating the user on each call he makes. When a user resets his password, his old password is still stored in the auth-cache, so he has to wait till it is evicted to log in using the new password. 

The solution: the intuitive solution is just to evict the user from the auth cache when resetting his password, the problem with this solution is that we might not necessarily have a centralized cache so we might need to evict the user for every auth cache he exists in. This is why the simpler solution here might be just to not use auth cache for email-password authentication. This way, we still won't need to authenticate when a user uses API calls that use access-key and secret for authentication and won't need to do the effort of evicting the user auth from all of the auth cache instances.

**Comment by nopcoder** [comment]
No cache is a valid solution. I think we will need to remove the option to use the email/password from the main API authentication middleware to reduce the lookup without cache for every call that will not fall into the key/secret happy path.

**Comment by arielshaqed** [comment]
Let's add this as a design in a PR under `design/open`.

The obvious issue is performance, which we would need to measure for web-based access.  We are assuming that the auth-server and its database can take the load.

Also,  _only_ the credentials (email+password) can remain uncached.  Everything else about the user should be cached -- otherwise users cannot run data-intensive workloads (which use an access key).  And we will need to enforce (or at least document explicitly) that using email+password may only be used for the GUI.
