### ISSUE TITLE
Failure in loading a user with % in their name

### ISSUE THREAD

**Issue by idanovo** [treeverse/lakeFS#3708]
1. Create an integration user with a name like idan%demo
2. Try to go click on the user that was created
Because % is a special character in URL, you will get an empty page

**Comment by eladlachmi** [comment]
This is an issue with `react-router-dom` (or any other history-based client-side router) and the interaction with the native history API. Discussion [here](https://github.com/remix-run/history/issues/505).  

There are some ways of working around this, but most are deep in "The remedy is worse than the disease" territory.  
Since the spec calls for using `%`-based encoding for URLs, this will always be an issue. I'm going to "fix" this by disallowing `%` to be used in user, group, or policy names. I don't believe this is an unreasonable constraint.  

Would be happy to get feedback on this, if anyone thinks differently or has another suggestion.

**Comment by arielshaqed** [comment]
> Would be happy to get feedback on this, if anyone thinks differently or has another suggestion.

I understand why react-router does this.  FWIW, it seems like a bug that stems from them wanting to make it "easier" to use in the sense of "working" both with paths that have been URI-encoded and that have not.

I agree that we cannot fix this in the GUI.  Regardless, since we are going into _**backend** data validation_ on this one, I believe the code that prevents percent signs from usernames needs a comment to point at the react-router documentation in the issue.  Otherwise it looks like we are trying to obfuscate that we have some encoding and/or injection bug.
