### ISSUE TITLE
Merge lakefs-samples repository with lakefs

### ISSUE THREAD

**Issue by adipolak** [treeverse/lakeFS#3757]
To demonstrate lakefs, we created multiple demos and scripts under https://github.com/treeverse/lakeFS-samples

To provide users with accessible samples of working with lakefs directly in the lakefs project. I suggest merging the two repositories.

Offered structure

-lakefs
--samples

Would appreciate your thoughts!

**Comment by arielshaqed** [comment]
@adipolak @nopcoder and I met and decided _not_ to do this for now.  In order to realize the gain we must first implement CI for everything in lakefs-samples; this is also pretty much a requirement for participating in lakeFS, which is an evergreen repository (in the sense that tests on trunk should always be green, and that trunk is ready to run)!
