### ISSUE TITLE
feature request: add STS endpoint to lakeFS

### ISSUE THREAD

**Issue by fcomte** [treeverse/lakeFS#3919]
Since lake is a S3 server, it could be usefull to be compliant to STS endpoint API calls

https://docs.aws.amazon.com/STS/latest/APIReference/API_Operations.html 

I particularly use the AssumeRoleWithWebIdentity with my S3 server (not lakeFS)

**Comment by arielshaqed** [comment]
@Jonathan-Rosenberg @guy-har this might be one way to advance on Delta integration.

_Personally_ I would probably prefer something more JWT-ish and based on the lakeFS API - otherwise we will end up adding the entire AWS IAM catalogue of services one bit at a time in order to support all coming use-cases.

**Comment by arielshaqed** [comment]
Probably want more user input, use-cases, and stories before we proceed on this.
