### ISSUE TITLE
lakeFS config struct as a singleton

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#4049]
It would be much easier if lakeFS configuration could be retrieved in the code from multiple locations.
However the current `config.NewConfig()` creates a race condition when initialized from more than a single thread.

**Comment by arielshaqed** [comment]
Please note that this is intentional! Having global access to Config encourages creating/fetching it as needed rather than injecting values from config. So all the advantages of global variables. And also all the disadvantages: if we do _this_ then testing becomes harder: no injection means no concurrent testing with different configs, explicit Config.Reset calls, etc. 

(Which is not to say it shouldn't be changed, only that there's a reason.)

**Comment by itaiad200** [comment]
I agree. @itai-david I think this originated from your comment on some PR. I'm closing it but feel free to reopen if you disagree.
