### ISSUE TITLE
Rename "lakefs init" to "lakefs setup"

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#468]
The command `lakefs init` should be renamed to `lakefs setup`, to keep consistency with the API.

**Comment by vigneshashokan** [comment]
Can I take a stab at this issue if it is still open?

**Comment by arielshaqed** [comment]
> Can I take a stab at this issue if it is still open?

Hi @vigneshashokan ,

Sure, please do.  Our [contributors guidelines](https://docs.lakefs.io/contributing) should make it easy to get started.  Make sure to join [our Slack](https://join.slack.com/t/lakefs/shared_invite/zt-g86mkroy-186GzaxR4xOar1i1Us0bzw), where you can get quick replies to any queries on #dev or the other channels.

See you soon!

**Comment by arielshaqed** [comment]
Best self-assign the issue, before someone else takes it :-)

**Comment by imtira** [comment]
I know this issue is assigned, but I haven't seen any activity this week and I've got the changes running 
locally. Would you be interested in merging https://github.com/imtira/lakeFS/tree/rename-init-468 instead @arielshaqed?

Also, with this change, should the `init` metric be renamed too? `init.go` contains

    stats.CollectEvent("global", "init")

as of now; my fork changes that to "setup".

**Comment by YaelRiv** [comment]
Thanks @imtira! Much appreciated. 

Let us first check with @vigneshashokan what is the status.

**Comment by vigneshashokan** [comment]
If the @imtira 's PR is already ready, please go ahead and merge it, fine by me :)

**Comment by arielshaqed** [comment]
@imtira that's a good PR, and we can merge it.  But we have a few things to get into order:
1. @ozkatz we need to change all assets to use the new verb.  I don't see any reference in our documentation to the old verb (quick-start uses the GUI), but I'm not sure we don't have assets outside of this repo.
2. @ozkatz @nopcoder if this were a version above 1.0.0 then we would have to turn this into a major version.  It could be a minor release if we kept the old name, even deprecated.  Should we do that?
3. @guy-har FYI if the sandbox shows off this command then it will need to change.

**Comment by nopcoder** [comment]
In order to make it easy, I think it should be in two steps - just to be user-friendly.
First, add a new command that will do the same and print out a deprecation warning and reference the new command (setup) from the old one (init).
It will enable us to fix all the scripts or outside usage of the command and the following task will remove the deprecated command.

**Comment by swapniljha001** [comment]
What's the current status of this issue?

**Comment by arielshaqed** [comment]
> What's the current status of this issue?

@imtira has an in-flight PR to handle it.  I hope e fixes comments there so that we can pull it soon.
