### ISSUE TITLE
Redis kv support 

### ISSUE THREAD

**Issue by splitice** [treeverse/lakeFS#4881]
Would redis (and redis compatible e.g KeyDb) kv stores be implementable?

Seems like it should be a good fit.

Also a question I had when looking through the kv architecture. What is the expected behaviour if a key was lost.

With some kv stores being eventual persistent would the goal (or behaviour) be for an effective rollback?

**Comment by eladlachmi** [comment]
Thanks for opening the issue, @splitice!  
Without deep-diving into all the details, I believe it's technically possible to create a KV implementation over Redis or anything with a Redis-compatible API.

However, that wouldn't be my first choice due to the eventual persistence. Since we use the KV store for all our metadata, losing a key can mean anything from losing a ref to an uploaded object, branch, commit, or even a permissions policy.  

If I were to use Redis, I'd turn on AOF. This has storage and performance implications.  
If we consider the default and recommended one-second fsync interval, the worst-case scenario is that you lose one second of written keys if an instance goes down. How big of a loss this would be is dependent on the velocity of the writes.   

lakeFS assumes consistency, so we don't currently handle these cases, and it would be up to you to handle the DR.  
Ultimately, it depends on your specific use case and your sensitivity to potential data loss vs. the upside of an in-memory KV store.

Internally, we're currently focused on the DynamoDB KV implementation. In the future, we might look into alternative implementations, including Redis, but I can't provide a timeline since it's currently not our focus.

Does that answer your question?
