### ISSUE TITLE
Discover API option: Write our own clients

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#4939]
## Definition of done

* [ ] Implement (or use existing!):
  * [ ] GetObject
  * [ ] UploadObject
  * [ ] (Optionally) something with streaming or pagination
* [ ] Use a single port on the lakeFS side
* [ ] Show calls from:
  * [ ] Web browser (GUI) [TypeScript]
  * [ ] Hadoop client (**without JNI!**) [Java]
* [ ] Object validation on client must be optional

**Comment by talSofer** [comment]
The actual work is to do: 
 Implement (or use existing!):
-  GetObject
-  UploadObject
-  (Optionally) something with streaming or pagination

Show calls from:
- Web browser (GUI) [TypeScript]
- Hadoop client (without JNI!) [Java]

And constraints are: 
- Use a single port on the lakeFS side
- Object validation on client must be optional

**Comment by lynnro314** [comment]
## Notes on client implementation

I implemented a new Java client, with GetObject and UploadObject methods, and tested it with a basic Java program that uses the client and uploads a file to lakeFS. 

### Optional parameters

Using params class that contains all parameters allows backward compatibility, and optional parameters are indeed optional:

Instead of `public CommitList logCommits(String repository, String ref, String after, Integer amount, List<String> objects, List<String> prefixes, Boolean limit) throws ApiException {`

We have `public CommitList logCommits(logCommitsParams params) throws ApiException {`
(“objects”, “prefixes” are not required!)

### Http client

Using [Apache http client](https://hc.apache.org/index.html) instead of OkHttp.
Explored the [options](https://www.twilio.com/blog/5-ways-to-make-http-requests-in-java), with emphasis on async requests. 
Apache http client:
* Uses future for async requests
* Supported in Java8 

#### Advantages 

* Control over implementation, allows clean code and understandable client.
* "Flat" client instead of multiple APIs:
    ```
    private final ObjectsApi objects;
    private final StagingApi staging;
    private final RepositoriesApi repositories;
    private final BranchesApi branches;
    ```

#### Disadvantages
* A lot of work.
  * Requires to implement all clients, and maintain them with every change. 
  * Current clients are not relevant as a reference.

**Comment by arielshaqed** [comment]
New client SDK is out :-)
