### ISSUE TITLE
GC fails for repositories with storage namespaces containing consecutive slashes

### ISSUE THREAD

**Issue by talSofer** [treeverse/lakeFS#4989]
Currently, lakeFS allows creating repositories with storage namespace consecutive slashes (e.g. s3://bucket/path**//**to/dir). However, while running GC for such repos it fails silently (because s3 does not error when it tries to delete a non-existing object).  

### Breadcrumbs for the root cause

On one hand, lakeFS writes objects to a path that does not include the consecutive slashes (i.e. s3://bucket/path**/**to/dir) because it is using a golang aws SDK that omits consecutive slashes although that graveler maps the repo into the storage namespace that includes consecutive slashes. On the other hand, GC uses java aws SDK client that behaves differently by not omitting the extra slashes. 

I suggest to disable to option to create storage namespaces containing consecutive slashes as a fix for this bug and to avoid similar inconsistencies in the future.

**Comment by arielshaqed** [comment]
I agree this bug is *not* in GC but rather in the AWS Go v1 SDK. The objects are created in the wrong storage namespace: user asked for 2 slashes but got one.

Given that this doing this is not particularly useful for users, and that it will be hard to fix without #2717 ... historically a tough one... I believe that we should prohibit creating such a namespace. We can also diagnose it in non-Go clients, maybe even strip the extra slashes, but that means users will get a repo that is unusable for some arbitrary features.
