### ISSUE TITLE
Add external authenticator support and deprecate LDAP

### ISSUE THREAD

**Issue by Isan-Rivkin** [treeverse/lakeFS#5262]
Follow up on https://github.com/treeverse/lakeFS/blob/master/CHANGELOG.md#unreleased

**Comment by vaskokj** [comment]
What does this mean? I'm using LDAP right now to provide access to users. Is this implying that it won't work any more? How is this new method supposed to work?

**Comment by ortz** [comment]
hey @vaskokj, how are you doing?

we're decoupling the security authentication and access control features from lakeFS, lakeFS will offer a pluggable way to add some features, we do this in order to allow us to focus better on our mission with lakeFS.
to your question, we're removing LDAP and OIDC embedded support from lakeFS.

If you currently rely on any of the deprecated features, please [contact us](mailto:support@treeverse.io?subject=RBAC+and+OIDC+deprecation) - we’ll do our best to support you in the transition.

if you're interested in discovering why we're doing this change and what's changing, you can read this [security update post](https://docs.lakefs.io/posts/security_update.html) on our site.

**Comment by vaskokj** [comment]
Thank you. I sent an email.Yeah, we use LDAP to allow users to login to lakeFS with their normal username and password that they use on a daily basis. Admins of LakeFS then can go and add users to specific projects/buckets as they need. So you are implying there will be another solution sorted out that will work similarly for lakeFS?-KevinOn Feb 19, 2023, at 9:35 AM, Or Tzabary ***@***.***> wrote:﻿
hey @vaskokj, how are you doing?
we're decoupling the security authentication and access control features from lakeFS, lakeFS will offer a pluggable way to add some features, we do this in order to allow us to focus better on our mission with lakeFS.
to your question, we're removing LDAP and OIDC embedded support from lakeFS.
If you currently rely on any of the deprecated features, please contact us - we’ll do our best to support you in the transition.
if you're interested in discovering why we're doing this change and what's changing, you can read this security update post on our site.
