### ISSUE TITLE
Support serve HTTPS without external SSL termination

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#5321]
Enabling TLS support for lakeFS

**Comment by arielshaqed** [comment]
I do not believe that lakeFS should support TLS termination.  It is creeping featurism, and it will **not** lead to increased security.

What is the use-case for this?  It must be...

* A single lakeFS server -- otherwise admins should put the cert on the load balancer; AND
* Open to the Internet -- otherwise admins should use VPCs / VLANs / whatever is available on their cloud;
* A well-secured lakeFS server machine.

Is this is worth the added complexity and support?

**Comment by nopcoder** [comment]
- https://lakefs.slack.com/archives/C016726JLJW/p1677102782579979
- secure communication using local certificate - as the same case for not having to setup nginx for small environment or local development.
- agree that for any cloud production environment I will opt for SSL termination by the load-balancer and not by the service itself.

**Comment by nopcoder** [comment]
@arielshaqed I think have the code support such option has low complexity and have more benefits than having to setup another component to enable secure communication.

**Comment by arielshaqed** [comment]
We cannot progress on this discussion.  I'm in the minority here so I will remove my objections.  Let's just document it clearly, preferably with a howto?

THANKS!
