### ISSUE TITLE
[Bug]: S3 fallback incorrectly validates credentials against lakeFS credentials before forwarding request

### ISSUE THREAD

**Issue by AdrianoKF** [treeverse/lakeFS#5359]
### What happened?

See description in [Slack](https://lakefs.slack.com/archives/C016726JLJW/p1677574899629609).
        
Steps to Reproduce:
1. Enable `gateways.s3.fallback_url` for an endpoint with credentials different from the ones used to access the lakeFS S3 API
2. Try to upload a file into an S3 URI that ends up on the fallback endpoint
3. Receive an `InvalidAccessKeyId` error (in `aws s3`)

### Expected Behavior

When providing correct credentials for the fallback S3 endpoint, uploading the file should work without an error.

### lakeFS Version

0.94.0

### Deplyoment

helm-chart

### Relevant logs output

```shell
time="2023-02-28T09:04:09Z" level=warning msg="could not find access key" func=pkg/gateway.AuthenticationHandler.func1 file="build/pkg/gateway/middleware.go:46" error="not found" key=[REDACTED]
```
```


### Contact Details

a.rumpold@gmail.com / lakeFS Slack: @Adrian Rumpold

**Comment by johnnyaug** [comment]
@AdrianoKF, thank you for opening this!
After looking a bit into it, I think it's not really a bug - more like a very lacking feature.
In order to decide whether or not to use the fallback, lakeFS has to check whether or not the repository exists. To do so, the request must be authenticated with lakeFS, and hence can't be authenticated with AWS at the same time. The original intention here was for it to be used in conjuction with an instance of a tool like [S3Proxy](https://github.com/gaul/s3proxy), which would handle the authentication with S3.

A direction we can take here would be to use the fallback also in case of an authentication failure.
