### ISSUE TITLE
display images in README.md

### ISSUE THREAD

**Issue by yokomeow** [treeverse/lakeFS#5366]
### Discussed in https://github.com/treeverse/lakeFS/discussions/5357

<div type='discussions-op-text'>

<sup>Originally posted by **yokomeow** February 28, 2023</sup>
Is it possible to paste images **from lakefs repo** in README.md from the same repo using markdown?
If yes, how to write an image path correctly?</div>

**Comment by yokomeow** [comment]
I mean I want to add images in readme file as usual you can do it on github, for example (see screenshot below). And the question is how can i do it in lakefs repo if i want to use image that is stored in lakefs repo?
Basically, i would add a line to readme file like "[!some image]\(lakefs://my_repo/main/image.png)", but this kind of path doesn't work. 
<img width="891" alt="Снимок экрана 2023-03-01 в 17 45 01" src="https://user-images.githubusercontent.com/32332255/222174139-fa7aabfb-bde0-4da6-8c7d-16a209e4af0a.png">

**Comment by yokomeow** [comment]
@itaiad200 hey! are there any updates about the issue?

**Comment by eladlachmi** [comment]
@itaiad200 The markdown is rendered client-side, so the browser has to have the ability to download the images once the HTML with the image tags is rendered from MD and injected into the DOM.  

I see two possible solutions here, each with its pros/cons:
1. Parse the markdown on the BE and replace `lakefs://...` URIs of images with presigned URLs
2. Create a plugin for the MD parser on the FE, which will replace those same URIs with presigned URLs, which it will request from the BE w/ GetObject and presign true

No. 1 is more efficient since presigned URLs are generated locally. However, the BE would need some content awareness, which isn't great.

No. 2 will impact render latency proportionally to the number of images used. However, I think it's the more logical place to put this substitution since it parses MD to HTML anyway.
