### ISSUE TITLE
Sample repository for new installs - cloud repository with hooks

### ISSUE THREAD

**Issue by ortz** [treeverse/lakeFS#5504]
### Goals
We'd like users to have the ability to explore and understand lakeFS' core features (creating a branch, reading and writing files, committing, merging) quickly (without the need to configure their infrastructure).

### Metrics
- Increase active installations
- Reduce time to activation

### Multiple Object Stores
Supporting multiple object stores might be complex as the import functionality works on the same object store only, so we might want to consider using native `lakectl fs` capabilities (e.g uploading objects), though this limits us to smaller files that will probably be delivered as part of the lakefs binary or downloaded remotely, which might raise security concerns.
If we do like to support multiple object stores, we'll probably need a dedicated skeleton store per object store to import from - this will be an advantage if we'd like to provide big data sets as part of the sample repo.

Another option is to have the two methods combined, provide sample hooks, readme, and small files as an example, and the readme will provide an example of how to import, depending on the object store being used.

### References
We can use the sample hooks from: https://github.com/treeverse/cloud-sample-repo-hooks/
We could also use the datasets mentioned in that repository (relevant to S3 only)

### Open Questions
- Should we create a sample repo out of the box?
  - If using the `local` adapter, this means creating files on the local filesystem (either server or desktop)
  - If using one of the object stores, this means to creating at least the metadata files there
  - Should we get the user contest for this?
- Should we let the user create a sample repo just like we do for template repositories?
- Should we do this as part of the provisioning phase? (admin user set up, it can be a checkbox "[x] Create a sample repository" or a flag for the `docker run` command)

### Needs discovery
- How do we maintain the docker run experience?
- Support only local? only s3?

**Comment by eladlachmi** [comment]
@ortz 
> admin user set up, it can be a checkbox "[x] Create a sample repository."

That's what I was thinking exactly.

I think that having a relatively small initial repo makes things easier to grasp and significantly lowers the operational complexity. 
We can clone it from a dedicated public repo, download from a public S3 bucket, or indeed embed it in the binary.
Also, using lakectl to upload seems like a good idea because it abstracts away the need to handle each blockstore implementation in the "initial repo creator."

**Comment by rmoff** [comment]
We can re-purpose the [new quickstart](https://docs.lakefs.io/quickstart/) for this sample repo. It includes a [sample data file](https://github.com/treeverse/lakeFS/blob/master/quickstart/lakes.parquet) and existing material on: 

* [Query](https://docs.lakefs.io/quickstart/query.html)
* [Branch](https://docs.lakefs.io/quickstart/branch.html)
* [Commit and Merge](https://docs.lakefs.io/quickstart/commit-and-merge.html)
* [Rollback](https://docs.lakefs.io/quickstart/rollback.html)

TODO: 

- [ ] Figure out how to enable the user to modify the data in a self-contained way without external deps (see below)
- [ ] Agree initial DX of creating user/repo (see below)
- [ ] Rewrite material into a README for the sample repo, using `<details><summary>` tags to collapse and show sections for readability and ease of use.
- [ ] Add hooks

## Making changes to the data

### Why?
* We want the user to be able to experience making a change to the existing data as they would in real life (and would do with a file in git branch)
* But, we need an engine to transform the data
* Quickstart uses duckDB but is a self-contained Docker Compose environment
	* For sample repo to work universally it can't rely on Docker

### Options
* Can we get DuckDB WASM to work for writing changes back to lakeFS? This would be the ideal (and great functionality for lakeFS UI in general, beyond the sample repo)
	* Blocker: https://github.com/duckdb/duckdb-wasm/issues/1207
* We ship duckDB binary with lakeFS and user interacts with it from CLI (adds ~20-30MB to the download; no idea what LOE this is to add to the build process)
* Present the user with a replacement file for them to upload which has changed values and the user can see the difference? Could be rather convoluted though

### Fallback option
* User just uploads a file, any file, into a new branch. They get to see the idea of committing a change, but quite easily miss the point of committing changes made to an existing file and seeing branch isolation in action

## User credentials and friction

If we're getting users to modify data and write it back to lakeFS, it's going to be outside of the UI's auth. That's because even if we used DuckDB WASM it'd still be using S3 and need the auth setting as part of it ([e.g.](https://docs.lakefs.io/quickstart/branch.html#setting-up-duckdb)). 

_With that given_, it's worth considering if we can have a fixed set of credentials (such as is enabled by the current `lakefs setup`), with the clear benefit of fixed details for the user to copy and paste in the examples. The alternative is the somewhat clunky and error-prone "_make a note of the key and secret / paste in your key and secret in these fields_" 

But, for us to do this we need to think about how and when the user and sample repo is being created. The above idea about only creating sample repo if a  checkbox is selected is based on the user running lakeFS _and then creating the user_ (and thus getting a unique set of creds). For us to have a fixed set of creds imagines that the user is spinning up a sandbox-only lakeFS (e.g. with `--local-settings`), and if they do this then we can just assume they we create a sample repo for them too. 

### My recommendation

1. We bake the fixed creds (`AKIA-EXAMPLE-KEY` / `EXAMPLE-SECRET` work well) into lakeFS binary so that when user invokes it with `lakefs setup --local-settings` the user is pre-created along with the sample repo. 

2. We change the flag from `--local-setting` to `--sandbox` to make it clearer that this is only for sandbox use. 

If felt necessary we could still make the sample repo available as a checkbox on setup, but would need to handle this in the deployed README so the file changed to tell the user to insert their own creds rather than fixed ones. 
This actually suggests one other option here: ignore my recommendation above, and only deploy the sample repo if the user checks a box when creating the user, _but embed their creds automagically in the relevant steps of the README_. However, storing creds in plain text in this way could be seen as a security risk or bad-practice at best.

**Comment by eladlachmi** [comment]
I see the sample parquet file is ~1MB. Considering this will be embedded in the lakeFS binary, I'd suggest using the smallest file possible, which still brings the user to that "Oh, I see the value!" moment.

**Comment by eladlachmi** [comment]
Adding mockups for "No repo" state and "new repository" dialog with sample data checkbox added + link to [Figma](https://www.figma.com/file/jahg27eCaiuRh4fvQ3HXln/First-Repository-Screen?type=design&node-id=63-742&t=TUhe0CBvCSsrU6et-0)

![Screenshot 2023-05-02 at 11 42 51](https://user-images.githubusercontent.com/110764839/235867362-e61e9d7e-e846-40c5-8bbb-5b2226332a57.png)

![Screenshot 2023-05-01 at 20 34 07](https://user-images.githubusercontent.com/110764839/235867417-87020183-ef74-4c6b-8ed9-48ebb0741bc6.png)

**Comment by rmoff** [comment]
- [ ] Update Docker image: 
  - [ ] Add DuckDB 
- [ ] Add data to get included with sample repo
- [ ] Update sample repo README from existing quickstart
- [ ] Check existing quickstart still works as-is
- [ ] Create a ticket to update the quickstart to be docker run only

**Comment by rmoff** [comment]
@eladlachmi  (/cc @ozkatz )

Just trying out the new change from #5787. I like the new landing page, it looks nice 👍 

I think we need two changes to make this as smooth as possible for the user. 

1. When `lakefs setup --local-settings` is called, also pre-create an admin user with creds `AKIA-EXAMPLE-KEY` / `EXAMPLE-SECRET`. This is what the quickstart [currently does](https://github.com/treeverse/lakeFS/blob/master/quickstart/docker-compose.yml#L19) and makes time-to-click much faster

3. When the user clicks **Create Sample Repository** it should just go ahead and create the repository. I'd suggest either quickstart or sample (I don't mind which). Making the user fill out another form just to enter a name adds more friction than necessary.

**Comment by ozkatz** [comment]
sample repos on s3 / other cloud storage require a storage namespace, so we need this dialog anyway. Perhaps it's OK to skip it on local installations? WDYT @eladlachmi

**Comment by eladlachmi** [comment]
@ozkatz @rmoff I'm worried about complicating this with all kinds of "special cases". As an alternative, maybe we can pre-populate the repo name with "sample", so essentially they don't need to do anything but click "Create Repository". WDYT?

**Comment by rmoff** [comment]
Ah good point about other namespaces. 

Can we skip it for local installations then please? 

@eladlachmi I take your point about complications, but `--local-settings` is already a special case in itself, and I think the trade-off for DX is worth it.

**Comment by rmoff** [comment]
alternative to this: 

> 1. When `lakefs setup --local-settings` is called, also pre-create an admin user with creds `AKIA-EXAMPLE-KEY` / `EXAMPLE-SECRET`. This is what the quickstart [currently does](https://github.com/treeverse/lakeFS/blob/master/quickstart/docker-compose.yml#L19) and makes time-to-click much faster

is we just add the user creation into the Docker image only

**Comment by rmoff** [comment]
Issues & ERs for the Web UI:  https://github.com/treeverse/lakeFS/issues/5798

**Comment by rmoff** [comment]
@eladlachmi @ozkatz coming back to the discussion on what happens when the user clicks "Create Sample Repository". 

Please can we either

1. (My preferred option) Check for local storage, and if so, don't show the `Create A New Repository` dialog and just go ahead and create `quickstart` repository pre-populated
2. (Fallback option) Still display the dialog, but if `sampleDataCheckbox` is checked, then pre-populate the `Repository ID` in the dialog with `quickstart`


thanks

**Comment by rmoff** [comment]
Thinking about it some more - we either hardcode the repo name (`quickstart`, for example) or we have to search & replace the deployed `README.md` at import time to fix it. There are too many references through the text to the repo name & screenshot otherwise and we also want to be able to link to objects within it.
