### ISSUE TITLE
[Question]:How can i use the other cloud  object store .

### ISSUE THREAD

**Issue by san5167** [treeverse/lakeFS#6022]
### What happened?

I want to store my data in other cloud object store，such as oos of alibabacloud .How can i do ?
Are there community had some docs  to explain this question or   introduce that how to design object store?

### Expected Behavior

Expected Behavior:
How you expected thing to work.

### lakeFS Version

v0.100.0

**Comment by arielshaqed** [comment]
Hi @san5167 !

Thanks for taking lakeFS out for a spin.  The keywords for searching on this repo are "Aliyun oss".  I'm afraid that we previously had mixed results with this, about a year ago, see #3614, #3613, #3490.

You will need to set `blockstore.s3.force_path_style` to `true` in your lakeFS conf file.  However this _might not be enough_, and will depend on your region.  Aliyun call host style "virtual host address", and we actually require _not_ to use it.

In particular when I previously communicated with Aliyun [it would only work in the Japan region](https://github.com/treeverse/lakeFS/issues/3614#issuecomment-1177648930).  Of course things may have changed since then.

As you can imagine, there are language and political barriers: I am unable to read Aliyun documentation in Chinese, and I was also not permitted to create any Aliyun objects on any region in mainland China.  But of course if you proceed I will help you as possible on the lakeFS side!

On the subject of language: apologies if I missed any diacritical marks, I am truly ignorant of Pinyin.

**Comment by san5167** [comment]
Thanks for you answer ，it is very helpful for me.
I have knew the Lakefs  basically  can not integrate OOS now in that you  introduced issue.
I will try how to integrate  OBS of Huaweiyun  to the Lakefs.

Pinyin of “Aliyun” is right👍👍。
It is nice to communicate with you。

**Comment by arielshaqed** [comment]
Thanks!  I will have to close this issue for now.  We will need involvement from Aliyun to resolve this.
