### ISSUE TITLE
Entry not found after delete entry on parent branch

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#619]
When we delete an entry that found on the parent branch the entry is not found on the previous branch commit.

Reproduce steps:
1. Create an entry on 'master' branch
1. Commit 'master' changes
1. Create a branch 'b1' from 'master'
1. Delete file from 'b1' branch
1. Commit 'b1' changes

At this point listing or getting the entry from the 'create branch' commit will return no such entry.

**Comment by nopcoder** [comment]
I'll start with the explanation of how we use min/max commit ID today:

min_commit:
  0 - uncommitted entry
  N - commit ID I start living

max_commit:
  0 - deleted (tombstone)
  N - until this commit ID am revlent (died after this one)

The min/max commit is the range where the entry is relevant - but there are edge cases - uncommitted and a tombstone that we render into specific values into these fields.
Not sure I have a better suggestion or names for these fields, maybe just split the special meaning into additional fields, but it might produce complexity on the queries.

**Comment by arielshaqed** [comment]
_Thanks!
Sorry for not being clear about my request.  I'll try to be more verbose.  I feel that the current state is fragile, in the sense that it breaks a lot.  I would like to find small changes to make it\ more robust.  These changes might make a difference, or of course any other change might be even better:

1. These semantics must be documented _in_ the code.
1. Ideally we would select values that make the regular ordering and semantics work consistently.  E.g I am sure these edge cases are necessary, i just don't understand _why_:
  a.  Why is "uncommitted" 0 and not +infinity (for a suitable value of infinity)?  Why wouldn't that make naïve range queries just work correctly?
  b. Similarly, why is the tombstone marked on max_commit, rather than on the record (e.g. by setting physical_path to NULL)?
1. A good way to resolve issues like this could be to define (SQL) functions in the DDL for _all_ access to `min_commit` and `max_commit`, and then never touching them directly anywhere else.  Or we could document them in the code in comments, and then apply white-box testing to the DB.

**Comment by arielshaqed** [comment]
Reopening to get attention; feel free to move to a different issue or to rename this one, whatever works.

**Comment by nopcoder** [comment]
@arielshaqed suggest closing this one and evaluate the above while implementing the new "lakeFS on the Rocks" as it doesn't hold the same semantics so the above should be solved.

**Comment by nopcoder** [comment]
Created issue #1084
