### ISSUE TITLE
[Feature Request]: Be able to undo a branch deletion

### ISSUE THREAD

**Issue by mhtrinh** [treeverse/lakeFS#6373]
It would be great if we can undo a branch deletion ? 
May be having an option to archive a branch. If the user really want to cleanup, she needs to go the archive "tab" to be able to delete complete the branch ?

**Comment by arielshaqed** [comment]
Nice, and also tricky to find a useful, correct, and performant solution!

What does git do? Nothing for this, but whenever I delete a branch or do something else that's horrible, I can use the reflog. The committed data itself exists, after all, it's just that I don't know it's digest

Now a true reflog doesn't work for lakeFS, because it's fairly tied up to the working tree, and we don't have a working tree. Keeping a list of the last N=10_000 branch heads accessed would be a fair approximation. But that means serializing access (not a problem in git because it's smaller and has a working tree).

Maybe design such a solution, but for most accesses update the log as best-effort? For most uses it's enough to be reliable only when we mutate the head - commit or merge or delete.

**Comment by itaiad200** [comment]
@ozkatz to prioritize.
