### ISSUE TITLE
`lakectl local clone` doesn't work for a single object but doesn't tell the user that

### ISSUE THREAD

**Issue by rmoff** [treeverse/lakeFS#6416]
```
$ lakectl local clone lakefs://quickstart/main/lakes.parquet ./quickstart/

Successfully cloned lakefs://quickstart/main/lakes.parquet to /Users/rmoff/quickstart.

Clone Summary:

No changes
$ 
```

```
$ ls -la /Users/rmoff/quickstart
total 8
drwxr-xr-x   3 rmoff  staff    96 16 Aug 10:36 .
drwxr-x---+ 86 rmoff  staff  2752 16 Aug 10:36 ..
-rw-r--r--   1 rmoff  staff   118 16 Aug 10:36 .lakefs_ref.yaml
```

This is very misleading: 

```
Successfully cloned lakefs://quickstart/main/lakes.parquet to /Users/rmoff/quickstart
```

since it didn't clone the object. In fact, it will happily report that it cloned an object that doesn't even exist: 

```
$ lakectl local clone lakefs://quickstart/main/foobar ./quickstart/

Successfully cloned lakefs://quickstart/main/foobar to /Users/rmoff/quickstart.

Clone Summary:

No changes
```

If `lakectl local` is only for cloning folders then it should perform some kind of validation. As a stop-gap measure, don't display `Successfully cloned` if there were no objects downloaded. 

Also the help text for `local clone` suggests that it *should* work for a single object ("clone a path")

```
$ lakectl local clone --help
Clone a path from a lakeFS repository into a new directory.
```

**Comment by ozkatz** [comment]
Yes, validation is indeed missing here - `lakectl local clone` should work on directories.

Since object stores don't _really_ have directories, an non-existent path should be treated as an empty directory, so in this case, cloning it will create an empty local tracked directory which you should be able to add files to and commit.

I think the edge case here is the ambiguity created by the fact that in an object store this set of files is legal:

```text
quickstart
quickstart/foo
```

While on an actual filesystem it isn't. In this case, I suggest we run a `stat` on the cloned path to make sure there isn't already an object at the cloned path.

@rmoff (and @N-o-Z) WDYT?

**Comment by rmoff** [comment]
what about in the example I'm trying to do - should it work for an object? 

```
lakefs://quickstart/main/lakes.parquet
```

**Comment by N-o-Z** [comment]
> Yes, validation is indeed missing here - `lakectl local clone` should work on directories.
> 
> Since object stores don't _really_ have directories, an non-existent path should be treated as an empty directory, so in this case, cloning it will create an empty local tracked directory which you should be able to add files to and commit.
> 
> I think the edge case here is the ambiguity created by the fact that in an object store this set of files is legal:
> 
> ```
> quickstart
> quickstart/foo
> ```
> 
> While on an actual filesystem it isn't. In this case, I suggest we run a `stat` on the cloned path to make sure there isn't already an object at the cloned path.
> 
> @rmoff (and @N-o-Z) WDYT?

Agree with this approach - we should stat the path, if it is an existing object - fail, otherwise treat it as a (potential) directory
