### ISSUE TITLE
When creating branch from the UI, select the default branch as source

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#652]
On create a new branch, the source branch default value should select the repository default branch

**Comment by haardikdharma10** [comment]
Hi @nopcoder, can you help me on getting started with this?

**Comment by ramesht007** [comment]
Hey @nopcoder , can I work on this.

**Comment by nopcoder** [comment]
yes, did you managed to run a local dev environment and see the issue?

**Comment by iamRishabh07** [comment]
Hi, @nopcoder  I would like to work on this issue

**Comment by nopcoder** [comment]
anybody who likes to work on this issue, thanks, I just need to know that you understand what is the problem and you have experience in React.

**Comment by adithyaakrishna** [comment]
Hi @nopcoder I've good experience in building React Apps, Some of my projects are in my profile [My Github Profile](https://github.com/adithyaakrishna)
I would like to work on this issue 🚀

**Comment by arc9693** [comment]
@nopcoder Hey. I ran on my local and observed the issue. This is where we need work:
https://github.com/treeverse/lakeFS/blob/bc2d841583bd1827fde07464bc6f6f0d4077d609/webui/src/components/BranchesPage.js#L29
We need to pass the value of the default branch name as an initial value to useState hook instead of null or some other way by which we update "selected" to the default branch, as soon as branches load in the following section:
https://github.com/treeverse/lakeFS/blob/bc2d841583bd1827fde07464bc6f6f0d4077d609/webui/src/components/RefDropdown.js#L174
I would like to work on this. I have experience in React.
