### ISSUE TITLE
API cleanup: consolidate repository level properties/metadata

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#6535]
The following API should be consolidated into update repository level properties:

```
getBranchProtectionRules
deleteBranchProtectionRules
createBranchProtectionRules
getGarbageCollectionRules
getGarbageCollectionConfig
```

**Comment by johnnyaug** [comment]
My thought was to just stack all of them into a new Swagger object:
```
    RepositorySettings:
      type: object
      properties:
        repository_metadata:
          $ref: "#/components/schemas/RepositoryMetadata"
        branch_protection_rules:
          type: array
          items:
            $ref: "#/components/schemas/BranchProtectionRule"
        garbage_collection_rules:
          $ref: "#/components/schemas/GarbageCollectionRules"
        garbage_collection_config:
          $ref: "#/components/schemas/GarbageCollectionConfig"
```

Then have GET/PUT endpoints that get/update these under `repositories/{repo}/settings`.
The PUT endpoint will only update the ones that are specified in the request.

**Comment by arielshaqed** [comment]
> My thought was to just stack all of them into a new Swagger object:
> 
> ```
>     RepositorySettings:
>       type: object
>       properties:
>         repository_metadata:
>           $ref: "#/components/schemas/RepositoryMetadata"
>         branch_protection_rules:
>           type: array
>           items:
>             $ref: "#/components/schemas/BranchProtectionRule"
>         garbage_collection_rules:
>           $ref: "#/components/schemas/GarbageCollectionRules"
>         garbage_collection_config:
>           $ref: "#/components/schemas/GarbageCollectionConfig"
> ```
> 
> Then have GET/PUT endpoints that get/update these under `repositories/{repo}/settings`. The PUT endpoint will only update the ones that are specified in the request.

This is really neat!  I like that it gives a uniform syntax to everything.

But I _don't_ like the asymmetry between GET and PUT, it feels very unRESTful.  How about:
* GET `repositories/{repo}/settings` returns all settings.
* GET `repositories/{repo}/settings/{setting}` returns that setting.
* PUT `repositories/{repo}/settings/{setting}` sets only that setting.

That I feel will truly be RESTful.  We omit one of the PUTs, because it rarely makes sense.  And we can add it later.

Going one step further, in future I want to have _user-defined metadata_ on repositories.  As an example, this might be where we store the location of `_lakefs_tables/` in the repository.  So maybe call the endpoint `repositories/{repo}/metadata/{key}`, and have special keys like `::lakefs::branch_protection_rules`.  The `::lakefs::` is "our" namespace, so even when we open it to users with their own keys, they will still never touch our keys.

**Comment by nopcoder** [comment]
@johnnyaug proposal will reduce the number of API we will need to support as the structure with optional fields will keep compatibility, easy to add and type safety without adding GET/PUT for each settings we like to add.

About repository metadata - if we plan to update all metadata as one document we can add such structure as an try in the repository settings or open api just for metadata.
Its a good time to update the create repository API and enable a way to update these metadata.

**Comment by johnnyaug** [comment]
## Decision
1. We will move all of the above APIs to be under `repositories/{repo}/settings/{setting}`. Each of these will support GET and PUT. Some will support DELETE.
2. Each of the GET methods will return a ETag header with a checksum representing the current state of the setting.
3. Each of the PUT ones will accept an optional If-Match header. If given, the setting will only be updated if the current setting matches the checksum. Otherwise, status 412 is returned.
4.  Branch protection rules will be updated together as a single object, not one by one as today.

**Comment by N-o-Z** [comment]
Adding my shnekel:

We recently added a repo metadata mechanism to save information about operations performed on repository.
We should take that into account and perhaps reuse the endpoint `/repositories/{repository}/metadata`
