### ISSUE TITLE
Bug: select using DuckDB - Invalid Input Error: No magic bytes found at end of file

### ISSUE THREAD

**Issue by nopcoder** [treeverse/lakeFS#6617]
Reported by user:
Following the quickstart tutorial, merged by the "denmark" branch into "main".
Using the UI's DuckDB `SELECT * FROM READ_PARQUET('lakefs://quickstart/main/lakes.parquet');`
Returns the following error:
`Error: Invalid Input Error: No magic bytes found at end of file 'lakefs://quickstart/main/lakes.parquet'`

**Comment by arielshaqed** [comment]
@nopcoder did we manage to fix this?  Please close if we did, unassign and we'll triage if not.
THANKS!

**Comment by nopcoder** [comment]
Not fixed - removed myself and added `ui` tag

**Comment by johnnyaug** [comment]
I was not able to reproduce this issue. I followed the quickstart tutorial and was able to query the main branch right after merging from the _denmark-lakes_ branch. 

In particular, there was no issues with caching: DuckDB caching is disabled by default, and browser cache is not a problem because the ETag of the file changes after the merge so the cache is not used.

I'm closing this issue now, feel free to re-open if more information is available. CC @nopcoder.
