### ISSUE TITLE
RBAC: Allow resource "arn:lakefs:fs:::repository/prefix*"

### ISSUE THREAD

**Issue by kesarwam** [treeverse/lakeFS#6716]
If I have many repositories then I want to control access on the subset of repositories based on the prefix. So, allow resource "arn:lakefs:fs:::repository/prefix*".

**Comment by iddoavn** [comment]
The reason here is that in some scenarios you will have hundreds of users and repositories. However, each user has access to a much smaller list of repos. Often, based on a prefix, that can be a department name, for example. This gets "noisy" fast, and would be better if users can only see their repositories.

**Comment by kesarwam** [comment]
This is needed to list the repositories

**Comment by iddoavn** [comment]
The challenge is not only the "noise" but also strictly separation of access. Users shouldn't see repositories that they have no access to.

**Comment by talSofer** [comment]
duplicate of https://github.com/treeverse/product/issues/181
