### ISSUE TITLE
Including PR and Issue templates to repo

### ISSUE THREAD

**Issue by Parikshit-Hooda** [treeverse/lakeFS#687]
Suggestion:
I think that as this repo grows, it could use formatted ways to handle issues and PRs. I'd like to work on including templates to implement this functionality. Examples of templates: [circuitverse](https://github.com/CircuitVerse/CircuitVerse/tree/master/.github)

**Comment by OmkarPh** [comment]
I would like to make these templates, can you assign it to me?

**Comment by arielshaqed** [comment]
Hi @iamrajiv, @OmkarPh ,
Thanks for your work on this!  We are trying to determine our requirements for handling PRs as part of our strategy for what information to include when releasing new versions.  We should have something in the next week or so that will be aligned with that strategy.
I'm closing this issue for now.  Please let us know on https://app.slack.com/client/T013V60QY06/C01APUNTSGH if you need help finding some other issues.
Thanks!

**Comment by OmkarPh** [comment]
Sure @arielshaqed 
We'll have eyes on the repo and work with some other issues.

Anyways, Happy Hacktoberfest 🎉
