### ISSUE TITLE
Python Wrapper: Discussion: Should we use DefaultClient as a global variable name

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#6998]

**Comment by N-o-Z** [comment]
Some examples of Python breaking their own PEP8 conventions:

Can find multiple examples in typing.py (created post PEP8 - so no backwards compatibility required)
One example is NamedTuple class decleration:
```
def NamedTuple(typename, fields=None, /, **kwargs):
```

**Comment by ozkatz** [comment]
My opinion is that I don't really care. There are examples out in the wild (and as @N-o-Z mentioned, also in the stdlib) where this is done this way. 

There's no product requirement for this, however - if you feel strongly about it being snake_case, go for it.

**Comment by N-o-Z** [comment]
@arielshaqed I lean towards closing this issue.
Another suggestion is to make the global variable into a function `def DefaultClient()` which returns the default client or None just as in the NamedTuple example.
Let me know what you prefer

**Comment by arielshaqed** [comment]
`NamedTuple` is explicitly the [name of a type](https://docs.python.org/3/library/typing.html?highlight=typing%20namedtuple#typing.NamedTuple) -- that's why it's in `typing`.  It is used as a type, and even when called as a function it returns a type.

```py
>>> nt = NamedTuple('TUV', [('a', str), ('b', int)])
>>> nt
<class '__main__.TUV'>
>>> type(nt)
<class 'type'>
```

Here we are talking about a global variable that holds an object.

There uses of default clients in real Python code, I searched for a few:

- lakefs_sdk (generated code) has a ApiClient.get_default class method (and a set_default, too).
- Boto autoloads a [`DEFAULT_SESSION`](https://boto3.amazonaws.com/v1/documentation/api/latest/_modules/boto3.html#setup_default_session).

**Comment by arielshaqed** [comment]
> @arielshaqed I lean towards closing this issue. Another suggestion is to make the global variable into a function `def DefaultClient()` which returns the default client or None just as in the NamedTuple example. Let me know what you prefer

I am explicitly opposed to a method named `DefaultClient`.  I would be happy with a method `default_client`, or possibly a global named `DEFAULT_CLIENT`.  An advantage of a method is that it makes creation explicit.

**Comment by N-o-Z** [comment]
> > @arielshaqed I lean towards closing this issue. Another suggestion is to make the global variable into a function `def DefaultClient()` which returns the default client or None just as in the NamedTuple example. Let me know what you prefer
> 
> I am explicitly opposed to a method named `DefaultClient`. I would be happy with a method `default_client`, or possibly a global named `DEFAULT_CLIENT`. An advantage of a method is that it makes creation explicit.

DEFAULT_CLIENT it is then...
