### ISSUE TITLE
[Bug]: tls: server sent certificate containing RSA key larger than 8192 bits

### ISSUE THREAD

**Issue by ingoke** [treeverse/lakeFS#7091]
### What happened?

Steps to Reproduce:
1. I've updated lakefs from v0.109.0 to v1.2.0 and lakectl from v0.104.0 to v1.2.0 
2. When executing any lakectl command I'm getting an error message about a RSA key which exceeds a key length of 8192 bits, e.g.

``
Warning: failed sending statistics: Post "https://.../api/v1/statistics": tls: server sent certificate containing RSA key larger than 8192 bits
Get "https://.../api/v1/auth/policies/...": tls: server sent certificate containing RSA key larger than 8192 bits
Error executing command.
``

### Expected behavior

I don't understand the limitation of the key length in the new version of lakectl. The CA certificates in the chain are longer than 4096 bits, but I can't change it. Switching back to lakectl v.0.104.0 "solves" the problem. 

### lakeFS version

1.2.0

### How lakeFS is installed

Kubernetes on-premise

### Affected clients

lakectl v1.2.0

### Relevant log output

```shell
Warning: failed sending statistics: Post "https://.../api/v1/statistics": tls: server sent certificate containing RSA key larger than 8192 bits
Get "https://.../api/v1/auth/policies/...": tls: server sent certificate containing RSA key larger than 8192 bits
Error executing command.
```

### Contact details

ingo.kemmerzell@gi-de.com

**Comment by nopcoder** [comment]
The error comes from Go's TLS package. You can set environment variable in order to override the limit. From the code doc:

```
In order to avoid denial of service attacks, the maximum RSA key size allowed in certificates sent by either the TLS server or client is limited to 8192 bits. This limit can be overridden by setting tlsmaxrsasize in the GODEBUG environment variable (e.g. GODEBUG=tlsmaxrsasize=4096).
```

**Comment by nopcoder** [comment]
@arielshaqed can we close this one, or there is anything actionable?

**Comment by arielshaqed** [comment]
AFAIK this is resolved by setting GODEBUG as above.

I'm closing, so here's a description that will hopefully make this issue more searchable or understandable.

## What's wrong?

A certificate with an RSA key larger than 8192 bits appears in the certificate chain.  Usually this will be the certificate of the root CA.  No public CAs have such large certificates, and this size is considerably larger than any NIST recommendation for key sizes.  This is [CVE-2023-29409](https://nvd.nist.gov/vuln/detail/CVE-2023-29409): sending such a certificate to a loaded client is an easy way to cause denial of service, because the client or server needs to validate the certificate to know the identity of the server.

Recent versions of the standard Go cryptography libraries fix this security bug and **refuse** to validate such large certificates.

## Workarounds

### Change certificates

There is no publicly-known reason to have an RSA key with 8192 bits, and certainly not more than that.  A summary of discussion with good references is on the [Wikipedia page](https://en.wikipedia.org/wiki/Key_size#Asymmetric_algorithm_key_lengths).

### Allow Go crypto to validate large certificates

Set a higher value in the GODEBUG environment variable, for instance
```sh
GODEBUG=tlsmaxrsasize=16384
```
See [Conn.Handshake](https://pkg.go.dev/crypto/tls#Conn.Handshake) documentation.

Note that this allows some DoS attacks during connection setup.
