### ISSUE TITLE
[Hi-lvl Python SDK] Handling file buffers on exceptions

### ISSUE THREAD

**Issue by nicholasjng** [treeverse/lakeFS#7195]
Back again with another transaction-related question. We currently have a finalizer logic in place, which allows the transaction to discard a buffer if it does not succeed (in reality, this means if an exception happened, i.e. if `sys.exc_info` is populated).

However, I do not see a way to discard a `WritableObject`'s buffer, outside of accessing the private spooled tempfile. Could you provide an API like `AbstractBufferedFile.discard()` in fsspec? https://github.com/fsspec/filesystem_spec/blob/master/fsspec/spec.py#L1701

Also currently, `__exit__`ing any IOBase object calls `close()`, which at least in the writeable object case results in an upload attempt regardless. If there's an exception (see the above point), a discard should in my opinion be preferred to the current behavior.

BTW - the current ObjectReader's `close()` also fails a cleanup test in our suite, meaning that on a failed read of a `StoredObject`, a local file descriptor is created that is never cleaned up. ([Source](https://github.com/aai-institute/lakefs-spec/blob/946da5e4301b319e018f5da2eed99c8a59c0f78b/tests/test_get_file.py#L21) for the failing test)

**Comment by N-o-Z** [comment]
Thanks again @nicholasjng,
Looking into this.

**Comment by N-o-Z** [comment]
@nicholasjng Opened https://github.com/treeverse/lakeFS/pull/7200 to address the issues here.
You can use the associated branch to see if your tests pass. 

Some questions:

> However, I do not see a way to discard a `WritableObject`'s buffer, outside of accessing the private spooled tempfile. Could you provide an API like `AbstractBufferedFile.discard()` in fsspec? https://github.com/fsspec/filesystem_spec/blob/master/fsspec/spec.py#L1701
> 

As you mentioned - we use a SpooledTemporaryFile object to maintain WritableObject's buffer. The SpooledTemporaryFile is being discarded once the object is closed. If I understand correctly, you want to be able to discard of the buffer in situations where you don't want to call `writer.close()`? If so what do you feel the expected behavior should be after discard?

- Should the writer be closed after discard? Should you be able to write after discard?

> BTW - the current ObjectReader's `close()` also fails a cleanup test in our suite, meaning that on a failed read of a `StoredObject`, a local file descriptor is created that is never cleaned up. ([Source](https://github.com/aai-institute/lakefs-spec/blob/946da5e4301b319e018f5da2eed99c8a59c0f78b/tests/test_get_file.py#L21) for the failing test)

Not sure why this is happening. ObjectReader doesn't open a file, it hold a `BytesIO` object as a read buffer and we are not writing anything to file.

**Comment by N-o-Z** [comment]
Hi @nicholasjng, 
Following up to make sure the new SDK release resolved all your issues and that you are on track

**Comment by nicholasjng** [comment]
Thanks @N-o-Z! New stuff works well, I finished migrating the package this week. I ran into a few things where I would have expected different behavior, I can post them as separate issues if you're interested.

**Comment by N-o-Z** [comment]
@nicholasjng 
1. That's great news! 🎉 
2. We're always happy to get more feedback. I would suggest referencing all of the concerns / questions / suggestions in a single issue and we can discuss them there.

Thanks again!
