### ISSUE TITLE
Support Azure Blob Storage other than default Azure Cloud

### ISSUE THREAD

**Issue by SpinoPi** [treeverse/lakeFS#7518]
We're in the process of configuring LakeFS on Azure China Cloud. However, we've hit a snag during the setup because the management endpoint for Azure Blob Storage in China ('blob.core.chinacloudapi.cn') differs from the default Azure cloud ('blob.core.windows.net'). As a result, we're facing issues when trying to create a new repository. Is there a way to bypass this validation step in LakeFS?

![图片](https://github.com/treeverse/lakeFS/assets/18522943/776a84c7-9464-4c49-9d94-01ca3c8fe296)

**Comment by itaiad200** [comment]
Hey @SpinoPi ! I tried tackling this in what I believed to be a quick fix in #7520. However this require some more work from our side to handle the different possible Azure URLs properly.

**Comment by itaiad200** [comment]
@SpinoPi lakeFS 1.13.0 is released today with experimental Azure China Cloud support. We haven't tested it since it takes us some time to provision a new cloud hosting. Can you check it out and see if it works? You'll need to add `blockstore.azure.china_cloud` to the server settings, full documentation on our server config can be found [here](https://docs.lakefs.io/reference/configuration.html).
