### ISSUE TITLE
Null Pointer exception when running spark garbage collection job

### ISSUE THREAD

**Issue by itaiad200** [treeverse/lakeFS#7911]

**Comment by arielshaqed** [comment]
Examining some backtrace, this might be not specifying the API URL in configuration, property spark.hadoop.lakefs.api.url or another property nearby.  This is specified e.g. [here](https://docs.lakefs.io/howto/garbage-collection/gc.html#how-to-run-the-garbage-collection-job).

In that case the issue here is to generate useful error messages for simple configuration errors.

**Comment by Isan-Rivkin** [comment]
Moving this issue to closed since it was a due to provided runtime dependencies issue of hadoop-aws and hadoop-common different versions.
