### ISSUE TITLE
Enhance UI tests to replace manual quickstart run when releasing OSS

### ISSUE THREAD

**Issue by yonipeleg33** [treeverse/lakeFS#7973]
Follow up on #7964

For context, see [this comment](https://github.com/treeverse/dev/pull/351#discussion_r1657585661) on the design proposal PR.

### Definition of done
We feel confident enough in the tests and CI that we don't need to manually run lakefs with `--quickstart` when releasing OSS.

### Current state
We have a minimal Playwright test suite that runs as part of the CI.
FWICT, the test suite runs against [DynamoDB kv store and local block store](https://github.com/treeverse/lakeFS/blob/67516d46bf1c49880d0967a6ed1b0c1f20a61052/.github/workflows/esti.yaml#L1051), and covers the setup page, repositories page, and querying an object:
```
$ tree webui/test/e2e/common                            
webui/test/e2e/common
├── README.md
├── readOnlyRepository.spec.ts
├── repositoriesPage.spec.ts
├── setup.spec.ts
└── viewParquetObject.spec.ts
```

### Tasks
1. Add tests or create a new test suite that covers at least "Query"( :heavy_check_mark: ), "Branch"(:x:), "Merge"(:x:), and "Rollback"(:x:) flows from the [quickstart guide](https://docs.lakefs.io/quickstart/)
2. Run them as part of the CI, in one of the following points:
   - As part of the goreleaser job - this is the minimal required frequency for running these tests.
   - On push to master - this ensures "releasability" of the master branch at any point in time.
   - On push to every branch (part of the CI job) - a bit excessive IMO, but a valid option as long as it doesn't become a bottleneck in the CI.

**Comment by Isan-Rivkin** [comment]
@yonipeleg33 Im a bit confused by this task definitions. 
1. Why do we need additional test to use `--quickstart` flag?  Since currently the e2e tests only difference is using dynamodb container. 
2. Is the current Playwright provide coverage for [quickstart](https://docs.lakefs.io/quickstart/)? in terms of functionality that we test or tests need to be added? 
3. Please clarify - what should be the deliverable of this task? a standalone ci job? part of some other workflow?

**Comment by yonipeleg33** [comment]
@Isan-Rivkin good points, I have updated the description as we discussed privately

**Comment by Isan-Rivkin** [comment]
@yonipeleg33 This looks very very clear THANK YOU!
