### ISSUE TITLE
Automate the goreleaser job

### ISSUE THREAD

**Issue by yonipeleg33** [treeverse/lakeFS#7976]
Follow up on #7964
Should come after #7975
For convenience, the job introduced in the above issue will be called "prepare release" in the context of this issue.

### Goals
1. Trigger the goreleaser job after the "prepare release" PR is merged
2. The goreleaser job creates the release asset
3. The goreleaser job creates a PR in the charts repository that bumps the new version

### Tasks
1. Inject the version and changelog by the prepare release job on the PR in away that the goreleaser job will know how to read when its triggered.
  Suggestion: Use comments, like shown in [this example](https://www.perplexity.ai/search/I-have-a-hSQLM9uXSbqA8jgjQBqL6w).
  On every push to this PR, a job (maybe the same "prepare release" job) will comment the version and changelog in their latest format on the PR, and the goreleaser job will read the latest comment from this PR.
2. Read the version and changelog in the goreleaser job when triggered.
3. Add a step to create the release asset in the goreleaser job
4.  Add a step to open a PR in the charts repository that bumps lakefs version to the provided version, and the chart version to the next patch.

**Comment by Isan-Rivkin** [comment]
This neat! But, some comments: 
1. Semantics but - "Automate the goreleaser job" the title is not clear - what does it mean? it's already automated job. What part of it lacks automation? Maybe a different workflow should **orchestrate between them**. 

2. Regarding [prepare release PR](https://github.com/treeverse/lakeFS/issues/7975)  - I think it should be all part of the same workflow run and actually run in opposite order -  think if a case where prepare PR finished but then release broke because it runs tests / generated code. So what I suggest is - only after the release artifacts are out (e.g binaries) then we create a PR with changelog and all.

**Comment by yonipeleg33** [comment]
As I discussed with @Isan-Rivkin, we are not sure yet how exactly would such automation work.
So I'm closing this issue, and we'll open a new one once we will have more clarity about the process.
