### ISSUE TITLE
Allow pushing data in the pre-commit hook

### ISSUE THREAD

**Issue by HMJiangGatech** [treeverse/lakeFS#8360]
In the pre-commit hook (e.g., lua hook), I'm looking for a way to write into the repo.

Example, I structure my repo as 
```
data/ # multiple json
stats.txt
```
Then I want to have a pre-commit hook to always count how many files in `data`, and write that into the stats.txt, e.g., 
```
Number of files in data/ are 107 .
```

I know I can publish somewhere else, e.g., a s3 location. But I'm looking for a solution to directly write into the repo.

**Comment by talSofer** [comment]
Thanks for opening this request @HMJiangGatech!

To assist in finding the right solution for your use case, do you mind answering these questions:
* At the end of what process are you committing? What does it do?
* How do you later use the file count in stats.txt?

I'm asking because the following solution may better fit your use case:
* Add a step to the process that modifies the `data/` prefix and make it update `stats.txt` with the file count 
* Implement a pre-commit hook that validates that `stats.txt `exists and was modified (rather than writing to lakeFS)

Do you think this would work for you?

**Comment by talSofer** [comment]
@HMJiangGatech happy to revisit or reopen when we get more context from your end
